// EJAC — GBJ, Quiz: perguntas gerais e dos livros pré-selecionados
// (Tobias, Evangelho de João, Efésios). Vieram de três fontes —
// "PERGUNTAS - JUREF - GBJ - 2026" (id 1 a 25 de cada seção),
// "PERGUNTAS GBJ EJAC" (id 26 a 50) e um lote escrito por revisão
// direta, sem PDF de origem (id 51 em diante, cada uma com um comentário
// "// fonte:" logo acima citando de onde veio, pra conferir) — juntados
// na mesma lista, mesmo formato. Cada pergunta tem um id estável
// (secao-numero) usado pra registrar contestação, então não muda a ordem
// nem os ids depois de publicado — só adicione no fim (ou continue a
// numeração de uma seção) se quiser crescer o banco de novo.
export const SECOES_QUIZ = {
  joao: 'Evangelho de João',
  tobias: 'Tobias',
  efesios: 'Efésios',
  gerais: 'Perguntas gerais',
};

export const PERGUNTAS_QUIZ = [
  {
    id: 'joao-1',
    secao: 'joao',
    pergunta: "QUANDO JOÃO BATISTA COMEÇOU A PREGAÇÃO QUEM OS JUDEUS ESTAVAM ESPERANDO? (JO 1,19-28)",
    alternativas: [
      "ELIAS",
      "O MESSIAS",
      "PROFETA",
      "JOÃO",
    ],
    correta: 1,
  },
  {
    id: 'joao-2',
    secao: 'joao',
    pergunta: "QUEM FOI ENVIADO POR DEUS PARA DAR TESTEMUNHO DE LUZ? (JO 1, 06-08)",
    alternativas: [
      "JOÃO",
      "PAULO",
      "PEDRO",
      "LUCAS",
    ],
    correta: 0,
  },
  {
    id: 'joao-3',
    secao: 'joao',
    pergunta: "SEGUNDO JOÃO COMO TERMINA A PRIMEIRA SEMANA DE JESUS? (JO 2, 01-12)",
    alternativas: [
      "CHAMANDO NATANAEL",
      "ENCONTRO DE JESUS E JOÃO",
      "BATISMO DE JESUS NAS ÁGUAS",
      "COM A FESTA DE CASAMENTO EM CANÁ",
    ],
    correta: 3,
  },
  {
    id: 'joao-4',
    secao: 'joao',
    pergunta: "QUANTAS JARRAS DE PEDRA TINHA NA FESTA DE CANA? (JO 2, 06)",
    alternativas: [
      "6",
      "7",
      "8",
      "9",
    ],
    correta: 0,
  },
  {
    id: 'joao-5',
    secao: 'joao',
    pergunta: "ONDE JESUS ESTAVA DURANTE A FESTA DA PÁSCOA? (JO 2, 23)",
    alternativas: [
      "NO SEPULCRO",
      "BELÉM",
      "TEMPLO",
      "JERUSALEM",
    ],
    correta: 3,
  },
  {
    id: 'joao-6',
    secao: 'joao',
    pergunta: "QUEM FOI PROCURAR JESUS DE NOITE PARA CONVERSAR? (JO 3, 01-02)",
    alternativas: [
      "HERÓDES",
      "JUDAS",
      "NICODEMOS",
      "PEDRO",
    ],
    correta: 2,
  },
  {
    id: 'joao-7',
    secao: 'joao',
    pergunta: "QUANTOS MARIDOS TEVE A SAMARITANA SEGUNDO JESUS? (JO 4, 16-18)",
    alternativas: [
      "2",
      "3",
      "4",
      "5",
    ],
    correta: 3,
  },
  {
    id: 'joao-8',
    secao: 'joao',
    pergunta: "O QUE JESUS DISSE SOBRE QUEM VEM A ELE? (JO 6, 37)",
    alternativas: [
      "VIDA ETERNA",
      "NUNCA SERÁ REJEITADO",
      "EU LHE DAREI DESCANSO",
      "BOM ÂNIMO",
    ],
    correta: 1,
  },
  {
    id: 'joao-9',
    secao: 'joao',
    pergunta: "ONDE JESUS EVITAVA ANDAR? (JO 7, 01)",
    alternativas: [
      "GALILEIA",
      "JERUSALÉM",
      "SAMARIA",
      "JUDEIA",
    ],
    correta: 3,
  },
  {
    id: 'joao-10',
    secao: 'joao',
    pergunta: "POR QUE JESUS EVITAVA ANDAR PELA JUDEIA? (JO 7, 01)",
    alternativas: [
      "POIS O POVO DE LÁ ERA IMPURO",
      "POIS O POVO DE LÁ QUERIA MATA-LÓ",
      "POIS O POVO NÃO ACEITAVA SUAS PREGAÇÕES",
      "POIS QUEM CUIDAVA DESSA REGIÃO ERAM OS APÓSTOLOS",
    ],
    correta: 1,
  },
  {
    id: 'joao-11',
    secao: 'joao',
    pergunta: "DE QUAL POVOADO LÁZARO ERA NATURAL? (JO 11, 01)",
    alternativas: [
      "JERUSALÉM",
      "GALILEIA",
      "BETÂNIA",
      "BABILÔNIA",
    ],
    correta: 2,
  },
  {
    id: 'joao-12',
    secao: 'joao',
    pergunta: "QUANTOS DIAS ANTES DA PÁSCOA JESUS FOI PARA BETÂNIA? (JO 12, 01)",
    alternativas: [
      "5 DIAS",
      "6 DIAS",
      "7 DIAS",
      "8 DIAS",
    ],
    correta: 1,
  },
  {
    id: 'joao-13',
    secao: 'joao',
    pergunta: "COM O QUE MARIA ENXUGOU OS PÉS UNGIDOS DE JESUS? (JO 12, 03)",
    alternativas: [
      "COM UM PANO",
      "COM UMA TOALHA",
      "COM AS VESTES",
      "COM SEU CABELO",
    ],
    correta: 3,
  },
  {
    id: 'joao-14',
    secao: 'joao',
    pergunta: "O QUE JESUS NOS DÁ? (JO 14, 27)",
    alternativas: [
      "SALVAÇÃO",
      "CURA",
      "PAZ",
      "PERDÃO",
    ],
    correta: 2,
  },
  {
    id: 'joao-15',
    secao: 'joao',
    pergunta: "QUAL O ADVOGADO QUE JESUS MANDA DE JUNTO DO PAI? (JO 15, 26)",
    alternativas: [
      "ESPÍRITO DA VERDADE",
      "ESPÍRITO SANTO",
      "VIRGEM MARIA",
      "DISCÍPULO JOÃO",
    ],
    correta: 0,
  },
  {
    id: 'joao-17',
    secao: 'joao',
    pergunta: "QUEM COLOCOU AS MÃOS NAS FERIDAS DE JESUS POIS NÃO ACREDITAVA NA RESSURREIÇÃO? (JO 20,24-29)",
    alternativas: [
      "PEDRO",
      "TOMÉ",
      "PAULO",
      "ZACARIAS",
    ],
    correta: 1,
  },
  {
    id: 'joao-18',
    secao: 'joao',
    pergunta: "QUAL O NOME DO LUGAR EM QUE JESUS FOI CRUCIFICADO? (JO 19,17)",
    alternativas: [
      "SEPULCRO",
      "HORTO DAS OLIVEIRAS",
      "LUGAR DA CAVEIRA",
      "LUGAR DA MORTE",
    ],
    correta: 2,
  },
  {
    id: 'joao-19',
    secao: 'joao',
    pergunta: "O QUE PILATOS MANDOU ESCREVER NA CRUZ DE JESUS? (JO 19, 19)",
    alternativas: [
      "EU SOU O REI DOS JUDEUS",
      "O FILHO DE DEUS",
      "REI DOS JUDEUS",
      "JESUS NAZARENO O REI DOS JUDEUS",
    ],
    correta: 3,
  },
  {
    id: 'joao-20',
    secao: 'joao',
    pergunta: "EM QUANTAS PARTES FORAM REPARTIDAS AS VESTES DE JESUS? (JO 19, 23)",
    alternativas: [
      "DUAS",
      "TRÊS",
      "QUATRO",
      "CINCO",
    ],
    correta: 2,
  },
  {
    id: 'joao-21',
    secao: 'joao',
    pergunta: "QUEM ESTAVA JUNTO A JESUS NA CRUZ? (JO 19, 25)",
    alternativas: [
      "SUA MÃE, MARIA MADALENA, MARIA DE CLÉOFAS",
      "SUA MÃE e MARIA MADALENA",
      "SUA MÃE, MARIA MADALENA e JOÃO",
      "SUA MÃE, MARIA DE CLÉOFAS e JOÃO",
    ],
    correta: 0,
  },
  {
    id: 'joao-22',
    secao: 'joao',
    pergunta: "A QUEM SE REFERE A SEGUINTE FRASE: ”EU DISSE ESSAS COISAS PARA QUE VOCÊS TENHAM MINHA PAZ. NESTE MUNDO VOCÊS TERÃO AFLIÇÕES, MAS TENHAM CORAGEM; EU VENCI O MUNDO. “ (JO 16, 33)",
    alternativas: [
      "AOS GALILEUS",
      "AOS DISCÍPULOS",
      "AOS PAGÃOS",
      "AOS JUDEUS",
    ],
    correta: 1,
  },
  {
    id: 'joao-23',
    secao: 'joao',
    pergunta: "QUEM DISSE A JESUS: A QUEM IREMOS, SENHOR? TU TENS PALAVRAS DE VIDA ETERNA. (JO 6, 68)",
    alternativas: [
      "JOÃO",
      "JUDAS",
      "TOMÉ",
      "PEDRO",
    ],
    correta: 3,
  },
  {
    id: 'joao-24',
    secao: 'joao',
    pergunta: "O QUE JESUS OFERECEU PARA MULHER SAMARITANA? (JO 4, 07-14)",
    alternativas: [
      "PÃO",
      "PEIXES",
      "ÁGUA",
      "ÓLEO DA UNÇÃO",
    ],
    correta: 2,
  },
  {
    id: 'joao-25',
    secao: 'joao',
    pergunta: "QUANTOS PÃES E PEIXES HAVIAM QUANDO JESUS ALIMENTOU A MULTIDÃO? (JO 6, 08)",
    alternativas: [
      "3 PÃES & 2 PEIXES",
      "4 PÃES & 2 PEIXES",
      "5 PÃES & 3 PEIXES",
      "5 PÃES & 2 PEIXES PERGUNTAS DE TOBIAS",
    ],
    correta: 3,
  },
  {
    id: 'tobias-1',
    secao: 'tobias',
    pergunta: "DE QUAL TRIBO DE ISRAEL TOBIT ERA DESCENDENTE? (TB 1,1-4)",
    alternativas: [
      "JUDÁ",
      "LEVI",
      "NEFTALI",
      "BENJAMIM",
    ],
    correta: 2,
  },
  {
    id: 'tobias-2',
    secao: 'tobias',
    pergunta: "PARA QUAL CIDADE TOBIT FOI LEVADO COMO EXILADO? (TB 1,2-3)",
    alternativas: [
      "JERUSALÉM",
      "NÍNIVE",
      "BELÉM",
      "RAGES",
    ],
    correta: 1,
  },
  {
    id: 'tobias-3',
    secao: 'tobias',
    pergunta: "O QUE TOBIT COSTUMAVA FAZER PELOS SEUS COMPATRIOTAS NECESSITADOS? (TB 1,16-18)",
    alternativas: [
      "COBRAR IMPOSTOS DELES",
      "DAR-LHES ALIMENTOS, ROUPAS E SEPULTAR OS MORTOS",
      "LEVÁ-LOS PARA JERUSALÉM",
      "TRABALHAR NO PALÁCIO DO REI POR ELES",
    ],
    correta: 1,
  },
  {
    id: 'tobias-4',
    secao: 'tobias',
    pergunta: "O QUE ACONTECEU COM TOBIT ENQUANTO DORMIA NO PÁTIO DE SUA CASA? (TB 2,9-10)",
    alternativas: [
      "FOI ATACADO POR UM ANIMAL",
      "FOI ROUBADO",
      "CAIU SOBRE ELE UMA ÁRVORE",
      "EXCREMENTOS DE PARDAIS CAÍRAM EM SEUS OLHOS, CAUSANDO SUA CEGUEIRA",
    ],
    correta: 3,
  },
  {
    id: 'tobias-5',
    secao: 'tobias',
    pergunta: "QUAL ERA O NOME DA ESPOSA DE TOBIT? (TB 1,9; 2,11-14)",
    alternativas: [
      "SARA",
      "EDNA",
      "ANA",
      "DÉBORA",
    ],
    correta: 2,
  },
  {
    id: 'tobias-6',
    secao: 'tobias',
    pergunta: "O QUE ANA RECEBEU COMO PAGAMENTO ALÉM DO DINHEIRO PELO TRABALHO QUE REALIZOU? (TB 2,11-13)",
    alternativas: [
      "UMA OVELHA",
      "UM CABRITO",
      "UM CORDEIRO",
      "UM BOI",
    ],
    correta: 1,
  },
  {
    id: 'tobias-7',
    secao: 'tobias',
    pergunta: "QUEM TAMBÉM REZOU A DEUS EM MEIO AO SOFRIMENTO NO MESMO DIA EM QUE TOBIT REZOU? (TB 3,7-10)",
    alternativas: [
      "EDNA",
      "ANA",
      "SARA",
      "DÉBORA",
    ],
    correta: 2,
  },
  {
    id: 'tobias-8',
    secao: 'tobias',
    pergunta: "QUANTOS HOMENS JÁ HAVIAM SIDO DADOS EM CASAMENTO A SARA ANTES DE TOBIAS? (TB 3,8; 6,14)",
    alternativas: [
      "CINCO",
      "SEIS",
      "SETE",
      "OITO",
    ],
    correta: 2,
  },
  {
    id: 'tobias-9',
    secao: 'tobias',
    pergunta: "QUE CONSELHO TOBIT DEU A TOBIAS A RESPEITO DE SUA MÃE? (TB 4,3-4)",
    alternativas: [
      "QUE A DEIXASSE MORAR SOZINHA",
      "QUE A HONRASSE E NUNCA A ABANDONASSE ENQUANTO ELA VIVESSE",
      "QUE A ENVIASSE PARA JERUSALÉM",
      "QUE LHE ENTREGASSE TODO O DINHEIRO",
    ],
    correta: 1,
  },
  {
    id: 'tobias-10',
    secao: 'tobias',
    pergunta: "O QUE TOBIT ACONSELHOU TOBIAS A FAZER QUANDO ENCONTRASSE UMA PESSOA POBRE? (TB 4,7-11)",
    alternativas: [
      "IGNORÁ-LA",
      "PEDIR QUE TRABALHASSE EM SUA CASA",
      "DAR ESMOLA CONFORME OS BENS QUE POSSUÍSSE",
      "MANDÁ-LA PROCURAR O REI",
    ],
    correta: 2,
  },
  {
    id: 'tobias-11',
    secao: 'tobias',
    pergunta: "QUAL PRINCÍPIO TOBIT ENSINOU A TOBIAS SOBRE O MODO DE TRATAR OS OUTROS? (TB 4,15)",
    alternativas: [
      "FAZER AOS OUTROS AQUILO QUE ELES FIZEREM PRIMEIRO",
      "NÃO FAZER A NINGUÉM AQUILO QUE NÃO GOSTARIA QUE FIZESSEM A ELE",
      "SEMPRE COLOCAR A PRÓPRIA VONTADE EM PRIMEIRO LUGAR",
      "NUNCA CONFIAR EM NINGUÉM",
    ],
    correta: 1,
  },
  {
    id: 'tobias-12',
    secao: 'tobias',
    pergunta: "QUANTO DINHEIRO TOBIT HAVIA DEIXADO EM DEPÓSITO COM GABAEL? (TB 4,20)",
    alternativas: [
      "CEM QUILOS DE PRATA",
      "DUZENTOS QUILOS DE PRATA",
      "TREZENTOS QUILOS DE PRATA",
      "QUINHENTOS QUILOS DE PRATA",
    ],
    correta: 2,
  },
  {
    id: 'tobias-13',
    secao: 'tobias',
    pergunta: "QUEM TOBIAS ENCONTROU QUANDO SAIU À PROCURA DE ALGUÉM PARA ACOMPANHÁ-LO ATÉ A MÉDIA? (TB 5,4-6)",
    alternativas: [
      "GABAEL",
      "RAFAEL, QUE SE APRESENTOU COMO AZARIAS",
      "RAGÜEL",
      "AICAR",
    ],
    correta: 1,
  },
  {
    id: 'tobias-14',
    secao: 'tobias',
    pergunta: "QUAL ANIMAL ACOMPANHOU TOBIAS E RAFAEL DURANTE A VIAGEM? (TB 6,1)",
    alternativas: [
      "UM CAVALO",
      "UM JUMENTO",
      "UM CACHORRO",
      "UM CAMELO",
    ],
    correta: 2,
  },
  {
    id: 'tobias-15',
    secao: 'tobias',
    pergunta: "O QUE TOBIAS ENCONTROU QUANDO ESTAVA LAVANDO OS PÉS NO RIO TIGRE? (TB 6,2-4)",
    alternativas: [
      "UMA SERPENTE",
      "UM GRANDE PEIXE",
      "UMA MOEDA",
      "UMA PEDRA PRECIOSA",
    ],
    correta: 1,
  },
  {
    id: 'tobias-16',
    secao: 'tobias',
    pergunta: "QUAIS PARTES DO PEIXE RAFAEL MANDOU TOBIAS GUARDAR? (TB 6,4-5)",
    alternativas: [
      "A CABEÇA, AS ESCAMAS E AS NADADEIRAS",
      "O SANGUE, OS OLHOS E OS OSSOS",
      "O FEL, O CORAÇÃO E O FÍGADO",
      "A PELE, AS ESCAMAS E O CORAÇÃO",
    ],
    correta: 2,
  },
  {
    id: 'tobias-17',
    secao: 'tobias',
    pergunta: "O QUE RAFAEL ACONSELHOU TOBIAS E SARA A FAZER ANTES DE SE UNIREM COMO MARIDO E MULHER? (TB 6,17-18)",
    alternativas: [
      "FAZER UMA VIAGEM",
      "OFERECER UM SACRIFÍCIO NO TEMPLO",
      "LEVANTAR-SE E REZAR, PEDINDO A MISERICÓRDIA E A PROTEÇÃO DO SENHOR",
      "ESPERAR SETE DIAS SEM CONVERSAR",
    ],
    correta: 2,
  },
  {
    id: 'tobias-18',
    secao: 'tobias',
    pergunta: "DE ACORDO COM O RELATO, O QUE ACONTECEU QUANDO TOBIAS COLOCOU O CORAÇÃO E O FÍGADO DO PEIXE NO QUEIMADOR DE INCENSO? (TB 8,2-3)",
    alternativas: [
      "O PEIXE VOLTOU À VIDA",
      "O DEMÔNIO FUGIU",
      "TOBIAS PERDEU A VISÃO",
      "SARA FICOU DOENTE",
    ],
    correta: 1,
  },
  {
    id: 'tobias-19',
    secao: 'tobias',
    pergunta: "O QUE TOBIAS E SARA FIZERAM JUNTOS DURANTE A NOITE DE NÚPCIAS? (TB 8,4-8)",
    alternativas: [
      "DORMIRAM IMEDIATAMENTE SEM CONVERSAR",
      "SAÍRAM DA CASA DE RAGÜEL",
      "REZARAM E PEDIRAM A PROTEÇÃO E A MISERICÓRDIA DE DEUS",
      "FORAM PROCURAR GABAEL",
    ],
    correta: 2,
  },
  {
    id: 'tobias-20',
    secao: 'tobias',
    pergunta: "COMO TOBIT RECUPEROU A VISÃO? (TB 11,7-13)",
    alternativas: [
      "PELA ORAÇÃO DE ANA",
      "POR MEIO DO FEL DO PEIXE APLICADO AOS SEUS OLHOS",
      "POR MEIO DE UMA CIRURGIA",
      "PELA IMPOSIÇÃO DAS MÃOS DE RAGÜEL",
    ],
    correta: 1,
  },
  {
    id: 'tobias-21',
    secao: 'tobias',
    pergunta: "QUEM REVELOU FINALMENTE SUA VERDADEIRA IDENTIDADE A TOBIT E TOBIAS? (TB 12,11-15)",
    alternativas: [
      "GABAEL",
      "RAGÜEL",
      "RAFAEL",
      "AICAR",
    ],
    correta: 2,
  },
  {
    id: 'tobias-22',
    secao: 'tobias',
    pergunta: "COM QUE IDADE TOBIT MORREU? (TB 14,1-2)",
    alternativas: [
      "100 ANOS",
      "105 ANOS",
      "112 ANOS",
      "120 ANOS",
    ],
    correta: 2,
  },
  {
    id: 'tobias-23',
    secao: 'tobias',
    pergunta: "POR QUE TOBIAS DECIDIU ACOMPANHAR O ANJO RAFAEL EM SUA VIAGEM? (TB 5,1-3)",
    alternativas: [
      "PARA VISITAR JERUSALÉM",
      "PARA RECUPERAR O DINHEIRO QUE TOBIT HAVIA DEIXADO COM GABAEL",
      "PARA PROCURAR UM EMPREGO NA MÉDIA",
      "PARA VISITAR RAGÜEL",
    ],
    correta: 1,
  },
  {
    id: 'tobias-24',
    secao: 'tobias',
    pergunta: "QUAL ERA O NOME DO PAI DE SARA? (TB 3,7; 6,9-12)",
    alternativas: [
      "TOBIT",
      "GABAEL",
      "RAGÜEL",
      "AICAR",
    ],
    correta: 2,
  },
  {
    id: 'tobias-25',
    secao: 'tobias',
    pergunta: "O QUE RAGÜEL FEZ QUANDO SOUBE QUE TOBIAS HAVIA CHEGADO À SUA CASA? (TB 7,1-6)",
    alternativas: [
      "MANDOU TOBIAS EMBORA",
      "RECEBEU TOBIAS COM ALEGRIA E O ACOLHEU",
      "PEDIU QUE TOBIAS VOLTASSE PARA NÍNIVE",
      "ENVIOU TOBIAS IMEDIATAMENTE A GABAE PERGUNTAS DE EFÉSIOS",
    ],
    correta: 1,
  },
  {
    id: 'efesios-1',
    secao: 'efesios',
    pergunta: "QUAL DAS CARTAS ABAIXO NÃO É UMA CARTA ESCRITA EM CATIVEIRO? (INTRODUÇÃO DO TEXTO)",
    alternativas: [
      "COLOSSENSES",
      "GÁLATAS",
      "FILIPENSES",
      "FELIMÔN",
    ],
    correta: 1,
  },
  {
    id: 'efesios-2',
    secao: 'efesios',
    pergunta: "SEGUNDO A INTRODUÇÃO DO TEXTO QUEM PROVAVELMENTE ESCREVEU A CARTA AOS EFÉSIOS? (INTRODUÇÃO DO TEXTO)",
    alternativas: [
      "LUCAS",
      "TÍQUICO",
      "UM DISCÍPULO DE PAULO",
      "O PRÓPRIO PAULO",
    ],
    correta: 2,
  },
  {
    id: 'efesios-3',
    secao: 'efesios',
    pergunta: "NA INTRODUÇÃO, O TEXTO APRESENTA A REGIÃO ONDE O AUTOR DO LIVRO MORAVA, QUE REGIÃO ERA ESSA? (INTRODUÇÃO DO TEXTO)",
    alternativas: [
      "LISTRA",
      "ANTIOQUIA",
      "CESARÉIA DE FILIPO",
      "VALE DO RIO LICO",
    ],
    correta: 3,
  },
  {
    id: 'efesios-4',
    secao: 'efesios',
    pergunta: "A CARTA AOS EFÉSIOS TRAZ PROBLEMAS GERAIS E NÃO APONTA NENHUM ERRO ESPECÍFICO DAQUELA COMUNIDADE, PORÉM TRAZ UM ALERTA. QUE ALERTA É ESSE? (INTRODUÇÃO DO TEXTO)",
    alternativas: [
      "AS FALSAS DOUTRINAS",
      "AS DEGRADAÇÕES MORAIS",
      "AO CULTO POLITEÍSTA",
      "AS PRÁTICAS PAGÃS",
    ],
    correta: 0,
  },
  {
    id: 'efesios-5',
    secao: 'efesios',
    pergunta: "SEGUNDO A INTRODUÇÃO, QUAL OUTRA CARTA EFÉSIOS TÊM SEMELHANÇA DOUTRINAL? (INTRODUÇÃO DO TEXTO)",
    alternativas: [
      "2 TESSALONICENSES",
      "GÁLATAS",
      "FILIPENSES",
      "COLOSSENSES",
    ],
    correta: 3,
  },
  {
    id: 'efesios-6',
    secao: 'efesios',
    pergunta: "POR VOLTA DE QUAL ANO FOI ESCRITO A CARTA AOS EFÉSIOS? (INTRODUÇÃO DO TEXTO)",
    alternativas: [
      "POR VOLTA DO ANO 70",
      "POR VOLTA DO ANO 90",
      "POR VOLTA DO ANO 60",
      "POR VOLTA DO ANO 80",
    ],
    correta: 1,
  },
  {
    id: 'efesios-7',
    secao: 'efesios',
    pergunta: "NO CAPÍTULO 2, QUAIS FORAM OS TRÊS PEDIDOS QUE PAULO FEZ A DEUS PARA A COMUNIDADE? (EF 2. NOTA DE RODAPÉ PAG 1427)",
    alternativas: [
      "PERSEVERANÇA, ILUMINAÇÃO E SABEDORIA",
      "COMPREENSÃO, AMOR E PACIÊNCIA",
      "SABEDORIA, ILUMINAÇÃO E COMPREENSÃO",
      "INTELIGÊNCIA, COMPREENSÃO E PERSEVERANÇA",
    ],
    correta: 2,
  },
  {
    id: 'efesios-8',
    secao: 'efesios',
    pergunta: "NO CAPÍTULO 2, COMO DEUS É DESCRITO PELO AUTOR? (EF 2, 4-7 NOTA DE RODAPÉ PAG. 1428)",
    alternativas: [
      "RICO EM MISERICÓRDIA, AMOR, FAVOR E BONDADE",
      "AMOR, BENEVOLÊNCIA, PAZ E CARIDADE",
      "BONDADE, JUSTIÇA, AMOR E PAZ",
      "JUSTIÇA, MISERICÓRDIA, AMOR E PACIÊNCIA",
    ],
    correta: 0,
  },
  {
    id: 'efesios-9',
    secao: 'efesios',
    pergunta: "SEGUNDO O AUTOR COMO OS GENTIOS ERAM CHAMADOS PELOS JUDEUS? (EF 2, 11)",
    alternativas: [
      "INCAPAZES",
      "INCIRCUNCIDADOS",
      "INCIRCUNCISOS",
      "IMPUROS",
    ],
    correta: 2,
  },
  {
    id: 'efesios-10',
    secao: 'efesios',
    pergunta: "COMO PAULO SE DESCREVE NO CAPÍTULO 3? (EF 3, 8)",
    alternativas: [
      "O MENOR DE TODOS OS ROMANOS",
      "O MENOR DE TODOS OS DISCÍPULOS",
      "O MENOR DE TODOS OS APÓSTOLOS",
      "O MENOR DE TODOS OS SANTOS",
    ],
    correta: 3,
  },
  {
    id: 'efesios-11',
    secao: 'efesios',
    pergunta: "QUANTOS CARISMAS SÃO ELENCADOS NO CAPÍTULO 4? (EF 4, 11)",
    alternativas: [
      "7 CARISMAS",
      "6 CARISMAS",
      "5 CARISMAS",
      "8 CARISMAS",
    ],
    correta: 2,
  },
  {
    id: 'efesios-12',
    secao: 'efesios',
    pergunta: "NO CAPÍTULO 4, PAULO COMENTA SOBRE A POSTURA DOS GENTIOS QUE VÃO ATRÁS DE PENSAMENTOS VAZIOS, E PEDE PARA QUE O POVO SE AFASTE DE ALGUMAS SITUAÇÕES. QUAIS SÃO ELAS? (EF 4, 31)",
    alternativas: [
      "IMORALIDADE, MESQUINHARIAS, IMPUREZAS, IRA E TODO TIPO DE MALDADE",
      "AMARGURA, IRA, CÓLERA, GRITARIA, DIFAMAÇÃO E TODO TIPO DE MALDADE",
      "OFENSAS, IMORALIDADE, IRA, IMPUREZAS E TODO TIPO DE MALDADE",
      "DESCONTROLE, CÓLERA, AMARGURA, IMPUREZAS E TODO TIPO DE MALDADE",
    ],
    correta: 1,
  },
  {
    id: 'efesios-13',
    secao: 'efesios',
    pergunta: "NO CAPÍTULO 5, PAULO PEDE PARA QUE A CAMINHADA DO POVO SEJA: (EF 5, 8)",
    alternativas: [
      "COMO FILHOS DA LUZ",
      "COMO FILHOS DA MISERICÓRDIA",
      "COMO FILHOS DA JUSTIÇA",
      "COMO FILHOS DA ESPERANÇA",
    ],
    correta: 0,
  },
  {
    id: 'efesios-14',
    secao: 'efesios',
    pergunta: "COMO PAULO COMPARA O CASAMENTO? (EF 5,21-33)",
    alternativas: [
      "COMO A IGREJA E OS APÓSTOLOS",
      "COMO A IGREJA E O PENTECOSTE",
      "COMO CRISTO E O BATISMO",
      "COMO CRISTO E A IGREJA",
    ],
    correta: 3,
  },
  {
    id: 'efesios-15',
    secao: 'efesios',
    pergunta: "O QUE PAULO PEDE PARA QUE NÃO SEJA, NEM SEQUER PRONUNCIADO, PELO POVO DE EFÉSO? (EF 5, 3)",
    alternativas: [
      "OFENSAS, NOME DE DEUSES DE OUTRAS REGIÕES E AVAREZA",
      "RELAÇÕES ILEGÍTIMAS, IMPUREZA E AVAREZA",
      "IMPUREZA, FALSO TESTEMUNHO, MESQUINHARIAS E IMORALIDADE",
      "RELAÇÕES ILEGÍTIMAS, IMORALIDADE, INDECÊNCIA E OFENSAS",
    ],
    correta: 1,
  },
  {
    id: 'efesios-16',
    secao: 'efesios',
    pergunta: "QUAL É O PRIMEIRO MANDAMENTO QUE INCLUI UMA PROMESSA, SEGUNDO PAULO? (EF 6, 2)",
    alternativas: [
      "NÃO LEVANTAR FALSO TESTEMUNHO",
      "AMAR A DEUS SOBRE TODAS AS COISAS",
      "HONRAR PAI E MÃE",
      "GUARDAR DOMINGOS E FESTAS",
    ],
    correta: 2,
  },
  {
    id: 'efesios-17',
    secao: 'efesios',
    pergunta: "COMO PAULO DIZ QUE O EVANGELHO DEVE SER ANUNCIADO? (EF 6, 19-20)",
    alternativas: [
      "COM ARDOR",
      "COM INTELIGÊNCIA",
      "COM SABEDORIA",
      "COM OUSADIA",
    ],
    correta: 3,
  },
  {
    id: 'efesios-18',
    secao: 'efesios',
    pergunta: "COM O QUE PAULO COMPARA A VIDA CRISTÃ? (EF 6, 10-17 NOTA DE RODAPÉ PÁG.1432)",
    alternativas: [
      "COM UM COMBATE",
      "COM UMA CAMINHADA",
      "COM UMA GUERRA",
      "COM UMA SUBIDA A MONTANHA",
    ],
    correta: 0,
  },
  {
    id: 'efesios-19',
    secao: 'efesios',
    pergunta: "QUEM É APONTADO COMO PORTADOR DA CARTA AOS EFÉSIOS? (INTRODUÇÃO DO TEXTO)",
    alternativas: [
      "LUCAS",
      "TEÓFILO",
      "MARCOS",
      "TÍQUICO",
    ],
    correta: 3,
  },
  {
    id: 'efesios-20',
    secao: 'efesios',
    pergunta: "NO CAPÍTULO 2 PAULO COMENTA QUE TODOS PODEM RECEBER A GRAÇA DA SALVAÇÃO. QUAIS POVOS SÃO CITADOS NESSE CAPÍTULO? (EF 2 – TÍTULO DO CAPÍTULO)",
    alternativas: [
      "ASSÍRIOS E MOABITAS",
      "JUDEUS E ASSÍRIOS",
      "JUDEUS E GENTIOS",
      "GENTIOS E ASSÍRIOS",
    ],
    correta: 2,
  },
  {
    id: 'efesios-21',
    secao: 'efesios',
    pergunta: "QUAL É A FINALIDADE DE VESTIR A ARMADURA DE DEUS? (EFÉSIOS 6,10-13)",
    alternativas: [
      "PARA VENCER OS HOMENS QUE SE OPÕEM À FÉ",
      "PARA RESISTIR ÀS MANOBRAS DO DIABO E PERMANECER FIRMES",
      "PARA ALCANÇAR SABEDORIA E CONHECIMENTO ESPIRITUAL",
      "PARA RECEBER OS DONS NECESSÁRIOS AO MINISTÉRIO",
    ],
    correta: 1,
  },
  {
    id: 'efesios-22',
    secao: 'efesios',
    pergunta: "O QUE ACONTECEU COM OS PAGÃOS POR MEIO DO EVANGELHO? (EFÉSIOS 3,6)",
    alternativas: [
      "TORNARAM-SE APENAS SEGUIDORES DA LEI DE MOISÉS",
      "RECEBERAM UMA PROMESSA DIFERENTE DA FEITA AOS JUDEUS",
      "FORAM CHAMADOS A PARTICIPAR DA MESMA HERANÇA, FORMAR O MESMO CORPO E PARTICIPAR DA MESMA PROMESSA",
      "FORAM ESCOLHIDOS PARA OCUPAR O LUGAR DOS APÓSTOLOS",
    ],
    correta: 2,
  },
  {
    id: 'efesios-23',
    secao: 'efesios',
    pergunta: "QUAIS SÃO OS FRUTOS DA LUZ? (EFÉSIOS 5,9)",
    alternativas: [
      "FÉ, ESPERANÇA E CARIDADE",
      "BONDADE, JUSTIÇA E VERDADE",
      "AMOR, PAZ E SABEDORIA",
      "JUSTIÇA, FÉ E OBEDIÊNCIA",
    ],
    correta: 1,
  },
  {
    id: 'efesios-24',
    secao: 'efesios',
    pergunta: "COM O QUE OS CRISTÃOS FORAM SELADOS DEPOIS DE OUVIR E ACREDITAR NO EVANGELHO? (EFÉSIOS 1,13-14)",
    alternativas: [
      "COM A GRAÇA DE DEUS",
      "COM O SANGUE DE CRISTO",
      "COM O ESPÍRITO SANTO DA PROMESSA",
      "COM A PALAVRA DA VERDADE",
    ],
    correta: 2,
  },
  {
    id: 'efesios-25',
    secao: 'efesios',
    pergunta: "O QUE PAULO RECOMENDA AOS FILHOS EM RELAÇÃO AOS PAIS? (EF 6,1-3)",
    alternativas: [
      "QUE SEJAM SUBMISSOS EM TODAS AS COISAS",
      "QUE OBEDEÇAM AOS PAIS NO SENHOR E OS HONREM",
      "QUE ENSINEM OS PAIS NA FÉ",
      "QUE DEIXEM SEUS PAIS PARA SEGUIR CRISTO PERGUNTAS GERAIS",
    ],
    correta: 1,
  },
  {
    id: 'gerais-1',
    secao: 'gerais',
    pergunta: "ESTAMOS EM QUAL EDIÇÃO DO ACAMPAMENTO DE CASAIS?",
    alternativas: [
      "ESTAMOS NA OITAVA EDIÇÃO",
      "ESTAMOS NA DÉCIMA EDIÇÃO",
      "ESTAMOS NA SEXTA EDIÇÃO",
      "ESTAMOS NA SÉTIMA EDIÇÃO",
    ],
    correta: 1,
  },
  {
    id: 'gerais-2',
    secao: 'gerais',
    pergunta: "QUAL É O DIA COMEMORADO PARA HOMENAGEM AO PROFETA ELIAS?",
    alternativas: [
      "21 DE JULHO",
      "20 DE JULHO",
      "22 DE JULHO",
      "23 DE JULHO",
    ],
    correta: 1,
  },
  {
    id: 'gerais-3',
    secao: 'gerais',
    pergunta: "QUAL FOI O DIA QUE FOI A DIVISÃO DAS PARÓQUIAS?",
    alternativas: [
      "05/03/2023",
      "06/03/2023",
      "07/03/2023",
      "08/03/2023",
    ],
    correta: 0,
  },
  {
    id: 'gerais-4',
    secao: 'gerais',
    pergunta: "QUAL É A DATA DE ANIVERSÁRIO DO GRUPO JUREF?",
    alternativas: [
      "5 DE ABRIL",
      "3 DE ABRIL",
      "2 DE ABRIL",
      "16 DE ABRIL",
    ],
    correta: 2,
  },
  {
    id: 'gerais-5',
    secao: 'gerais',
    pergunta: "QUAL É O DIA DO PADRE?",
    alternativas: [
      "5 DE AGOSTO",
      "4 DE AGOSTO",
      "6 DE AGOSTO",
      "7 DE AGOSTO",
    ],
    correta: 1,
  },
  {
    id: 'gerais-6',
    secao: 'gerais',
    pergunta: "QUAL DIA FOI A CRISTOTECA DE 2023?",
    alternativas: [
      "12 DE AGOSTO",
      "8 DE AGOSTO",
      "4 DE AGOSTO",
      "10 DE AGOSTO",
    ],
    correta: 0,
  },
  {
    id: 'gerais-7',
    secao: 'gerais',
    pergunta: "QUAL FOI O ÚLTIMO ACAMPAMENTO ANTES DA PANDEMIA?",
    alternativas: [
      "FAC",
      "MIRIM",
      "CES",
      "JUVENIL",
    ],
    correta: 1,
  },
  {
    id: 'gerais-8',
    secao: 'gerais',
    pergunta: "QUAL É O DIA DA BENÇÃO DOS ANIMAIS NA COMUNIDADE SÃO FRANCISCO DE ASSIS?",
    alternativas: [
      "3 DE OUTUBRO",
      "5 DE OUTUBRO",
      "4 DE OUTUBRO",
      "6 DE OUTUBRO",
    ],
    correta: 2,
  },
  {
    id: 'gerais-9',
    secao: 'gerais',
    pergunta: "QUAL SIGNIFICADO DOS TRÊS NÓS NO CORDÃO DE SÃO FRANCISCO?",
    alternativas: [
      "AMOR, OBEDIÊNCIA E CASTIDADE",
      "HUMILDADE, OBEDIÊNCIA E CASTIDADE",
      "POBREZA, OBEDIÊNCIA E CASTIDADE",
      "SOLIDARIEDADE, OBEDIÊNCIA E CASTIDADE",
    ],
    correta: 2,
  },
  {
    id: 'gerais-10',
    secao: 'gerais',
    pergunta: "QUANDO FOI A SEMANA DA FAMÍLIA NO ANO DE 2022?",
    alternativas: [
      "13 Á 21 DE AGOSTO",
      "07 Á 14 DE AGOSTO",
      "10 Á 17 DE AGOSTO",
      "12 Á 19 DE AGOSTO",
    ],
    correta: 0,
  },
  {
    id: 'gerais-11',
    secao: 'gerais',
    pergunta: "QUAL A DATA DO RETIRO VOCACIONAL CARMELITA EM 2017?",
    alternativas: [
      "21 Á 23 DE JULHO",
      "20 Á 24 DE JULHO",
      "22 Á 24 DE JULHO",
      "20 Á 22 DE JULHO",
    ],
    correta: 0,
  },
  {
    id: 'gerais-12',
    secao: 'gerais',
    pergunta: "O QUE LEVOU SANTA TEREZINHA ATÉ A MORTE?",
    alternativas: [
      "FOI PERSEGUIDA E MORTA POR HOMENS QUE NÃO GOSTAVAM DE JESUS",
      "GRIPE",
      "TUBERCULOSE",
      "SOFREU UM DERRAME",
    ],
    correta: 2,
  },
  {
    id: 'gerais-13',
    secao: 'gerais',
    pergunta: "QUAL A PADROEIRA DO PARANÁ?",
    alternativas: [
      "NOSSA SENHORA DO PERPÉTUO SOCORRO",
      "NOSSA SENHORA DA LUZ DOS PINHAIS",
      "NOSSA SENHORA AUXILIADORA",
      "NOSSA SENHORA DO ROCIO",
    ],
    correta: 3,
  },
  {
    id: 'gerais-14',
    secao: 'gerais',
    pergunta: "QUEM CANONIZOU SANTA TERESINHA?",
    alternativas: [
      "FOI O PAPA PIO XI",
      "FOI O PAPA PIO XII",
      "FOI O PAPA PIO X",
      "FOI O PAPA PIO VII",
    ],
    correta: 0,
  },
  {
    id: 'gerais-15',
    secao: 'gerais',
    pergunta: "QUAL ERA O NOME DE SÃO FRANCISCO?",
    alternativas: [
      "GIOVANNI DI PIETRO",
      "FRANCISCO DE ASSIS",
      "GIOVANNE DE PIETRO",
      "DJIOVANNE DE PIETRO",
    ],
    correta: 0,
  },
  {
    id: 'gerais-16',
    secao: 'gerais',
    pergunta: "QUAL O VERDADEIRO NOME DE SANTO ANTÔNIO?",
    alternativas: [
      "FERNANDO",
      "FRANCISCO",
      "FREDERICO",
      "LUCAS",
    ],
    correta: 0,
  },
  {
    id: 'gerais-17',
    secao: 'gerais',
    pergunta: "EM QUAL DIA EM 2025 FOI FEITO O TERÇO LUMINOSO NA COMUNIDADE SÃO FRANCISCO DE ASSIS?",
    alternativas: [
      "12 DE AGOSTO",
      "11 DE AGOSTO",
      "10 DE AGOSTO",
      "05 DE AGOSTO",
    ],
    correta: 0,
  },
  {
    id: 'gerais-18',
    secao: 'gerais',
    pergunta: "O QUE SIGNIFICA A PALAVRA CARMELO?",
    alternativas: [
      "MONTE",
      "ESPERANÇA",
      "JARDIM",
      "HARMONIA",
    ],
    correta: 2,
  },
  {
    id: 'gerais-19',
    secao: 'gerais',
    pergunta: "QUAL FOI A EDIÇÃO DE 2025 DA SJJ?",
    alternativas: [
      "DÉCIMA TERCEIRA",
      "DÉCIMA QUARTA",
      "DÉCIMA QUINTA",
      "NONA",
    ],
    correta: 1,
  },
  {
    id: 'gerais-20',
    secao: 'gerais',
    pergunta: "ONDE FICA O MONTE CARMELO?",
    alternativas: [
      "EGITO",
      "ISRAEL",
      "GRÉCIA",
      "ROMA",
    ],
    correta: 1,
  },
  {
    id: 'gerais-21',
    secao: 'gerais',
    pergunta: "QUAIS SÃO OS DOIS SACRAMENTOS DE SERVIÇO?",
    alternativas: [
      "EUCARISTIA E CRISMA",
      "ORDEM E MATRIMÔNIO",
      "BATISMO E CRISMA",
      "BATISMO E CONFISSÃO",
    ],
    correta: 1,
  },
  {
    id: 'gerais-22',
    secao: 'gerais',
    pergunta: "QUAL É A COR QUE USAMOS PARA OS MÁRTIRES?",
    alternativas: [
      "ROXO",
      "VERMELHO",
      "BRANCO",
      "VERDE",
    ],
    correta: 1,
  },
  {
    id: 'gerais-23',
    secao: 'gerais',
    pergunta: "QUAIS SÃO OS DONS DO ESPÍRITO SANTO?",
    alternativas: [
      "SABEDORIA, ENTENDIMENTO, CONSELHO, FORTALEZA, AMOR DE DEUS, PIEDADE E CIÊNCIA",
      "ENTENDIMENTO, CONSELHO, CIÊNCIA, TEMOR DE DEUS, FORTALEZA, PAZ E PIEDADE",
      "CIÊNCIA, SABEDORIA, TEMOR DE DEUS, FORTALEZA, PIEDADE, ENTENDIMENTO E CONSELHO",
      "FORTALEZA, TEMOR DE DEUS, CARIDADE, PIEDADE, CIÊNCIA, SABEDORIA E TEMOR DE DEUS",
    ],
    correta: 2,
  },
  {
    id: 'gerais-24',
    secao: 'gerais',
    pergunta: "QUANTOS SÃO OS SACRAMENTOS DA INICIAÇÃO CRISTÃ?",
    alternativas: [
      "2 SACRAMENTOS",
      "3 SACRAMENTOS",
      "4 SACRAMENTOS",
      "5 SACRAMENTOS",
    ],
    correta: 1,
  },
  {
    id: 'gerais-25',
    secao: 'gerais',
    pergunta: "QUANTAS ETAPAS DA CATEQUESE SÃO NECESSÁRIAS PARA FAZER O SACRAMENTO DA CONFIRMAÇÃO?",
    alternativas: [
      "3 ETAPAS",
      "4 ETAPAS",
      "5 ETAPAS",
      "6 ETAPAS",
    ],
    correta: 2,
  },
  {
    id: 'joao-26',
    secao: 'joao',
    pergunta: "Quais foram os 2 primeiros discípulos de Jesus?",
    alternativas: [
      "Pedro e André",
      "André e Tiago",
      "André e João",
      "Pedro e João",
    ],
    correta: 2,
  },
  {
    id: 'joao-27',
    secao: 'joao',
    pergunta: "Quantas talhas d’água foram enchidas nas Bodas de Caná? E quantas medidas cada uma continha?",
    alternativas: [
      "3 talhas, 3 a 4 medidas",
      "6 talhas, 2 a 3 medidas",
      "4 talhas, 3 a 4 medidas",
      "5 talhas, 2 a 3 medidas",
    ],
    correta: 1,
  },
  {
    id: 'joao-28',
    secao: 'joao',
    pergunta: "Quantos litros continham cada medida?",
    alternativas: [
      "40 litros",
      "36 litros",
      "50 litros",
      "28 litros",
    ],
    correta: 0,
  },
  {
    id: 'joao-29',
    secao: 'joao',
    pergunta: "Quantos anos levou para ser construído o templo de Jerusalém?",
    alternativas: [
      "48 anos",
      "53 anos",
      "39 anos",
      "46 anos",
    ],
    correta: 3,
  },
  {
    id: 'joao-30',
    secao: 'joao',
    pergunta: "A que figura do Êxodo, Jesus se compara ao dizer que seria levantado?",
    alternativas: [
      "Moisés",
      "Bezerro de Ouro",
      "Serpente de Bronze",
      "Tábuas da Lei",
    ],
    correta: 2,
  },
  {
    id: 'joao-31',
    secao: 'joao',
    pergunta: "Qual o nome da cidade onde Jesus se encontrou com a Samaritana?",
    alternativas: [
      "Enom",
      "Cesaréia",
      "Salim",
      "Sicar",
    ],
    correta: 3,
  },
  {
    id: 'joao-32',
    secao: 'joao',
    pergunta: "Quantos pórticos havia no tanque onde o paralítico havia sido curado? E quantos anos faziam desde que ele estava doente?",
    alternativas: [
      "6 pórticos e 27 anos",
      "4 pórticos e 32 anos",
      "3 pórticos e 38 anos",
      "5 pórticos e 38 anos",
    ],
    correta: 3,
  },
  {
    id: 'joao-33',
    secao: 'joao',
    pergunta: "Jesus afirma ser um só com o Pai, pois:",
    alternativas: [
      "tudo o que o Pai faz Ele faz também",
      "Ele reflete a imagem do Pai",
      "foi enviado para mostrar o amor ao próximo",
      "Seu testemunho é complexo",
    ],
    correta: 0,
  },
  {
    id: 'joao-34',
    secao: 'joao',
    pergunta: "O que significa “Filho do Homem”?",
    alternativas: [
      "Filho de Deus",
      "Messias",
      "Profeta das Nações",
      "Filho de um homem",
    ],
    correta: 1,
  },
  {
    id: 'joao-35',
    secao: 'joao',
    pergunta: "“200 denários de pão não lhes bastam, para que cada um receba um pedaço”, disse André durante a última ceia. A afirmação está:",
    alternativas: [
      "Correta, pois André sabia que faltaria alimento para a ceia",
      "Incorreta, pois quem disse isso foi Pedro durante a multiplicação dos pães",
      "Correta, pois além de pão precisavam de outras coisas",
      "Incorreta, pois isso foi dito por Felipe durante a multiplicação dos pães",
    ],
    correta: 3,
  },
  {
    id: 'joao-36',
    secao: 'joao',
    pergunta: "Jesus disse ser o pão do céu, ele compara isso ao:",
    alternativas: [
      "alimento em fartura do Jardim do Éden",
      "cordeiro imolado por Abraão",
      "o Maná do deserto",
      "os pães da proposição comidos por Davi",
    ],
    correta: 2,
  },
  {
    id: 'joao-37',
    secao: 'joao',
    pergunta: "Quais eram as medidas do lago de Tiberíades?",
    alternativas: [
      "25x11Km",
      "35x28km",
      "12x24Km",
      "38x53Km",
    ],
    correta: 0,
  },
  {
    id: 'joao-38',
    secao: 'joao',
    pergunta: "O que é a festa dos tabernáculos?",
    alternativas: [
      "Festa realizada em agosto, onde os judeus comemoram a vitória de Ester sobre Hamã",
      "Festa realizada em maio, onde os judeus recordam a entrega dos 10 mandamentos a Moisés",
      "Festa realizada em setembro, onde os judeus celebram o perdão dos pecados",
      "Festa realizada em setembro, onde os judeus recordam os 40 anos no deserto",
    ],
    correta: 3,
  },
  {
    id: 'joao-39',
    secao: 'joao',
    pergunta: "Jesus disse ser maior que Abraão pois:",
    alternativas: [
      "Abraão era indigno de respeito",
      "Abraão foi apenas uma ferramenta",
      "Ele existia muito antes de quer Abraão nascesse",
      "Ele não gostava do que Abraão significava",
    ],
    correta: 2,
  },
  {
    id: 'joao-40',
    secao: 'joao',
    pergunta: "Além da deficiência, o que o cego e o paralítico têm em comum?",
    alternativas: [
      "Foram forçados a difamar Jesus",
      "Foram curados em um sábado",
      "Foram ferramentas pra controle de massa",
      "Foram testemunhas a favor de Jesus durante seu julgamento",
    ],
    correta: 1,
  },
  {
    id: 'joao-41',
    secao: 'joao',
    pergunta: "No capítulo 10, Jesus diz ser o que? E por qual motivo?",
    alternativas: [
      "A porta estreita, pois sua palavra é justa",
      "A água viva, pois quem bebe dele nunca mais terá sede",
      "O bom pastor, pois ele dá a vida por suas ovelhas",
      "O cordeiro de Deus, pois ele tira todo o pecado mundo",
    ],
    correta: 2,
  },
  {
    id: 'joao-42',
    secao: 'joao',
    pergunta: "Qual era a distância entre Betânia e Jerusalém?",
    alternativas: [
      "13 estádios, 2km",
      "18 estádios, 3km",
      "10 estádios, 4km",
      "15 estádios, 3km",
    ],
    correta: 3,
  },
  {
    id: 'joao-43',
    secao: 'joao',
    pergunta: "Do que era feito a mistura que Maria, irmã de Lázaro, banhou os pés de Jesus? E qual era a quantidade?",
    alternativas: [
      "Aloés, 2 arrobas",
      "Aceto, 1 litro",
      "Bálsamo, 1 libra",
      "Fel, 2 pesos",
    ],
    correta: 2,
  },
  {
    id: 'joao-44',
    secao: 'joao',
    pergunta: "Qual foi o último mandamento dado por Jesus?",
    alternativas: [
      "Amar a Deus sobre todas as coisas",
      "Honrar o seu próximo como queres ser honrado",
      "Amar o próximo como ele nos amou",
      "Dar ajuda aos necessitados de coração",
    ],
    correta: 2,
  },
  {
    id: 'joao-45',
    secao: 'joao',
    pergunta: "Onde Pedro negou Jesus pela segunda vez?",
    alternativas: [
      "Na porta do sumo sacerdote",
      "Ao redor da fogueira",
      "No sinédrio",
      "No palácio de Herodes",
    ],
    correta: 1,
  },
  {
    id: 'joao-46',
    secao: 'joao',
    pergunta: "Como Jesus foi sepultado?",
    alternativas: [
      "Enrolado em panos e aromas",
      "Vestido com uma túnica de costura única e banhado numa mistura de aloés",
      "Com a cabeça envolta em um pano de linho e os pés banhados de perfume caro",
      "Com as pernas e braços atados por um fio, seguindo costumes judaicos",
    ],
    correta: 0,
  },
  {
    id: 'joao-47',
    secao: 'joao',
    pergunta: "Qual capítulo concluí o Evangelho de São João?",
    alternativas: [
      "22",
      "21",
      "19",
      "20",
    ],
    correta: 3,
  },
  {
    id: 'joao-48',
    secao: 'joao',
    pergunta: "Qual o maior capítulo do Evangelho de São João?",
    alternativas: [
      "7, 52",
      "9, 48",
      "18, 65",
      "6, 71",
    ],
    correta: 3,
  },
  {
    id: 'joao-49',
    secao: 'joao',
    pergunta: "O evangelho de São João foi escrito quanto tempo depois dos 3 outros evangelhos?",
    alternativas: [
      "15 anos",
      "30 anos",
      "27 anos",
      "9 anos",
    ],
    correta: 1,
  },
  {
    id: 'joao-50',
    secao: 'joao',
    pergunta: "Qual o livro subsequente e o antecessor ao Evangelho de São João?",
    alternativas: [
      "Romanos e Mateus",
      "Lucas e I Coríntios",
      "Atos e Lucas",
      "Marcos e Lucas",
    ],
    correta: 2,
  },
  {
    id: 'tobias-26',
    secao: 'tobias',
    pergunta: "Quando foi escrito o livro de Tobias?",
    alternativas: [
      "Século V a.C",
      "Século III a.C",
      "Século II a.C",
      "Século XV a.C",
    ],
    correta: 2,
  },
  {
    id: 'tobias-27',
    secao: 'tobias',
    pergunta: "Em qual idioma o livro de Tobias foi escrito originalmente?",
    alternativas: [
      "Aramaico",
      "Latim",
      "Grego antigo",
      "Hebraico",
    ],
    correta: 0,
  },
  {
    id: 'tobias-28',
    secao: 'tobias',
    pergunta: "Tobit pertencia a qual tribo de Israel?",
    alternativas: [
      "Simeão",
      "Judá",
      "Manassés",
      "Neftali",
    ],
    correta: 3,
  },
  {
    id: 'tobias-29',
    secao: 'tobias',
    pergunta: "Qual rei fez os bezerros de ouro para serem adorados?",
    alternativas: [
      "Nabucodonosor",
      "Salmanasar",
      "Jeroboão",
      "Senaquerib",
    ],
    correta: 2,
  },
  {
    id: 'tobias-30',
    secao: 'tobias',
    pergunta: "Qual foi a quantia que Tobit deu a Gabael?",
    alternativas: [
      "5 moedas de bronze",
      "10 talentos de prata",
      "12 moedas de ouro",
      "8 siclos de cobre",
    ],
    correta: 1,
  },
  {
    id: 'tobias-31',
    secao: 'tobias',
    pergunta: "Qual foi o ocorrido que deixou Tobit cego?",
    alternativas: [
      "Uma forte luz lhe atingiu os olhos",
      "Uma queda",
      "Esterco de andorinhas lhe caiu sobre os olhos",
      "A visão de um anjo",
    ],
    correta: 2,
  },
  {
    id: 'tobias-32',
    secao: 'tobias',
    pergunta: "Qual o significado do nome Rafael, anjo que apareceu a Tobias, em hebraico?",
    alternativas: [
      "Deus conosco",
      "Deus cura",
      "Deus salva",
      "Deus habita",
    ],
    correta: 1,
  },
  {
    id: 'tobias-33',
    secao: 'tobias',
    pergunta: "Qual foi o nome utilizado pelo anjo Rafael ao se apresentar a Tobias?",
    alternativas: [
      "Azarias, filho de Neemias",
      "Zacarias, filho de Esdras",
      "Jeremias, filho de Baruc",
      "Azarias, filho de Hananias",
    ],
    correta: 3,
  },
  {
    id: 'tobias-34',
    secao: 'tobias',
    pergunta: "Quais foram as partes do peixe que o anjo pediu que Tobias guardasse?",
    alternativas: [
      "Coração, fígado e fel",
      "Cabeça, fígado e fel",
      "Coração, rins e fel",
      "Cabeça, rins e fel",
    ],
    correta: 0,
  },
  {
    id: 'tobias-35',
    secao: 'tobias',
    pergunta: "O que Raguel fez quando Tobias e Sara entraram na câmara nupcial?",
    alternativas: [
      "Mandou que matassem três carneiros para festejarem o casamento de sua filha",
      "Cavou uma sepultura",
      "Pediu à sua esposa que preparasse um banquete",
      "Glorificou a Deus pelo casamento de sua filha",
    ],
    correta: 1,
  },
  {
    id: 'tobias-36',
    secao: 'tobias',
    pergunta: "Ao entrar nos aposentos de Sara para a noite de núpcias, qual a primeira coisa que Tobias fez?",
    alternativas: [
      "Pediu a Sara que rezasse com ele por 3 noites",
      "Colocou o coração do peixe sobre brasas acesas",
      "Glorificou ao Senhor",
      "Colocou o fígado do peixe sobre brasas acesas",
    ],
    correta: 3,
  },
  {
    id: 'tobias-37',
    secao: 'tobias',
    pergunta: "Raguel: \"Disse à sua mulher que aprontasse um banquete e preparasse todos os víveres necessários aos viajantes. Mandou também matar... :",
    alternativas: [
      "3 cordeiros e 2 vacas gordas",
      "2 vacas gordas e 4 carneiros",
      "3 vacas gordas e 5 carneiros",
      "2 cordeiros e 2 vacas gordas",
    ],
    correta: 1,
  },
  {
    id: 'tobias-38',
    secao: 'tobias',
    pergunta: "Com qual idade Tobit, pai de Tobias, morreu?",
    alternativas: [
      "110 anos",
      "120 anos",
      "112 anos",
      "90 anos",
    ],
    correta: 2,
  },
  {
    id: 'tobias-39',
    secao: 'tobias',
    pergunta: "Por qual outro nome Edna, mãe de Sara, pode ser chamada?",
    alternativas: [
      "Judite",
      "Ana",
      "Rute",
      "Ester",
    ],
    correta: 1,
  },
  {
    id: 'tobias-40',
    secao: 'tobias',
    pergunta: "Quanto tempo demorou até que o fel do peixe curasse a cegueira de Tobit?",
    alternativas: [
      "Cerca de meia hora",
      "1 dia inteiro",
      "Cerca de 1 hora",
      "Ele foi curado imediatamente",
    ],
    correta: 0,
  },
  {
    id: 'tobias-41',
    secao: 'tobias',
    pergunta: "Sara chegou à casa de seu sogro quantos dias após a chegada de Tobias?",
    alternativas: [
      "5 dias",
      "7 dias",
      "12 dias",
      "3 dias",
    ],
    correta: 1,
  },
  {
    id: 'tobias-42',
    secao: 'tobias',
    pergunta: "Qual o maior capítulo do livro de Tobias?",
    alternativas: [
      "4, 16",
      "7, 25",
      "5,28",
      "13, 19",
    ],
    correta: 2,
  },
  {
    id: 'tobias-43',
    secao: 'tobias',
    pergunta: "Quais são os menores capítulos do livro de Tobias?",
    alternativas: [
      "14,17 e 18,17",
      "2,15 e 12,15",
      "7,14 e 13,14",
      "9,12 e 10,12",
    ],
    correta: 3,
  },
  {
    id: 'tobias-44',
    secao: 'tobias',
    pergunta: "Quantos anos Tobit tinha quando ficou cego?",
    alternativas: [
      "75",
      "62",
      "112",
      "52",
    ],
    correta: 1,
  },
  {
    id: 'tobias-45',
    secao: 'tobias',
    pergunta: "Quantas gerações após a sua Tobias viu nascer?",
    alternativas: [
      "3",
      "4",
      "5",
      "6",
    ],
    correta: 2,
  },
  {
    id: 'tobias-46',
    secao: 'tobias',
    pergunta: "A quais figuras do antigo testamento o livro se refere ao mencionar \"Patriarcas\"?",
    alternativas: [
      "Abraão, Isaac e Jacó",
      "Isaac, Noé e Jacó",
      "Moisés, Jacó e Abraão",
      "Abraão, José e Davi",
    ],
    correta: 0,
  },
  {
    id: 'tobias-47',
    secao: 'tobias',
    pergunta: "Qual o livro subsequente ao livro de Tobias?",
    alternativas: [
      "Ester",
      "Judite",
      "Neemias",
      "Jó",
    ],
    correta: 1,
  },
  {
    id: 'tobias-48',
    secao: 'tobias',
    pergunta: "Qual o livro Anterior ao livro de Tobias?",
    alternativas: [
      "Reis",
      "Rute",
      "Neemias",
      "Esdras",
    ],
    correta: 2,
  },
  {
    id: 'tobias-49',
    secao: 'tobias',
    pergunta: "Qual demônio matou os 7 maridos de Sara?",
    alternativas: [
      "Belial",
      "Behemoth",
      "Asmodeu",
      "Astaroth",
    ],
    correta: 2,
  },
  {
    id: 'tobias-50',
    secao: 'tobias',
    pergunta: "Com quantos anos Tobias morreu?",
    alternativas: [
      "109",
      "99",
      "112",
      "129",
    ],
    correta: 1,
  },
  {
    id: 'efesios-26',
    secao: 'efesios',
    pergunta: "Em quais anos o apóstolo Paulo foi preso em Éfeso e em Roma, respectivamente?",
    alternativas: [
      "40 e 60 d.C",
      "60 e 62 d.C",
      "52 e 54 d.C",
      "59 e 63 d.C",
    ],
    correta: 1,
  },
  {
    id: 'efesios-27',
    secao: 'efesios',
    pergunta: "Segundo Paulo, Deus Pai nos escolheu para sermos:",
    alternativas: [
      "Santos e irrepreensíveis",
      "Corajosos e virtuosos",
      "Imitadores de Cristo",
      "Astutos e resilientes",
    ],
    correta: 0,
  },
  {
    id: 'efesios-28',
    secao: 'efesios',
    pergunta: "Atualmente, onde está localizada a cidade de Éfeso?",
    alternativas: [
      "Na Índia",
      "Na Etiópia",
      "Na Grécia",
      "Na Turquia",
    ],
    correta: 3,
  },
  {
    id: 'efesios-29',
    secao: 'efesios',
    pergunta: "O que Paulo pedia em suas orações para a comunidade de Éfeso?",
    alternativas: [
      "Paz e harmonia",
      "Sabedoria e compaixão",
      "Sabedoria e conhecimento de Deus",
      "Inteligência e fortaleza",
    ],
    correta: 2,
  },
  {
    id: 'efesios-30',
    secao: 'efesios',
    pergunta: "A que Paulo se refere quando fala sobre potestades do ar?",
    alternativas: [
      "Pragas",
      "Demônios",
      "Anjos",
      "Doenças",
    ],
    correta: 1,
  },
  {
    id: 'efesios-32',
    secao: 'efesios',
    pergunta: "Paulo diz ao Efésios que a nossa salvação provém pela:",
    alternativas: [
      "Obras",
      "Atos de caridade",
      "Graça",
      "Fé",
    ],
    correta: 3,
  },
  {
    id: 'efesios-33',
    secao: 'efesios',
    pergunta: "Paulo pede aos Efésios para que sejam solícitos em conservar:",
    alternativas: [
      "A pureza da alma no seu interior",
      "A unidade do Espírito no vinculo da paz",
      "A caridade com os mais necessitados",
      "O cuidado com aquilo nos vem do alto",
    ],
    correta: 3,
  },
  {
    id: 'efesios-34',
    secao: 'efesios',
    pergunta: "Por qual motivo Paulo diz que Cristo destruiu o muro da inimizade que separava os pagãos e os judeus?",
    alternativas: [
      "Porque havia um muro que separava as duas regiões",
      "Porque pela Redenção se tornaram uma só família",
      "Porque antes de sua morte Cristo fez um acordo de paz entre os dois lados",
      "Porque após a ressurreição Cristo ordenou que houvesse paz",
    ],
    correta: 1,
  },
  {
    id: 'efesios-35',
    secao: 'efesios',
    pergunta: "Qual salmo é mencionado na carta aos Efésios?",
    alternativas: [
      "Salmo 67, 19",
      "Salmo 53, 15",
      "89, 4",
      "103, 5",
    ],
    correta: 0,
  },
  {
    id: 'efesios-36',
    secao: 'efesios',
    pergunta: "De que maneira Paulo recebeu o chamado para revelar a união entre os pagãos e judeus?",
    alternativas: [
      "Por sonho",
      "Por um encontro com um anjo",
      "por revelação",
      "Pela oração",
    ],
    correta: 2,
  },
  {
    id: 'efesios-37',
    secao: 'efesios',
    pergunta: "Qual foi a missão que Paulo recebeu?",
    alternativas: [
      "Anunciar o Evangelho aos judeus",
      "Edificar uma nova igreja",
      "Restaurar os princípios ensinados pelos discípulos",
      "Anunciar o Evangelho aos pagãos",
    ],
    correta: 3,
  },
  {
    id: 'efesios-38',
    secao: 'efesios',
    pergunta: "Paulo pede aos Efésios para que se revistam do homem novo em:",
    alternativas: [
      "Coragem e justiça",
      "Justiça e santidade",
      "Caridade e compaixão",
      "Amor e ternura",
    ],
    correta: 1,
  },
  {
    id: 'efesios-39',
    secao: 'efesios',
    pergunta: "De onde vinha a glória da comunidade de Éfeso?",
    alternativas: [
      "Tribulações de Paulo",
      "Do pão partilhado",
      "Do amor ao próximo",
      "Da renúncia ao pecado",
    ],
    correta: 0,
  },
  {
    id: 'efesios-40',
    secao: 'efesios',
    pergunta: "No final do capítulo 3 Paulo queria que os Efésios tivessem conhecimento do que?",
    alternativas: [
      "Da importância da oração",
      "Da humildade de Cristo",
      "Da caridade de Cristo",
      "Importância da doação",
    ],
    correta: 2,
  },
  {
    id: 'efesios-41',
    secao: 'efesios',
    pergunta: "Segundo Paulo, Cristo corresponde à que parte da Igreja?",
    alternativas: [
      "Mãos",
      "Pés",
      "Tronco",
      "Cabeça",
    ],
    correta: 3,
  },
  {
    id: 'efesios-42',
    secao: 'efesios',
    pergunta: "De que maneira Paulo diz que os novos convertidos devem agir?",
    alternativas: [
      "Julgando os não – convertidos",
      "Perdoando uns aos outros",
      "Espalhando a Boa Nova",
      "Vivendo como viviam antes",
    ],
    correta: 1,
  },
  {
    id: 'efesios-43',
    secao: 'efesios',
    pergunta: "Quais são os frutos da luz?",
    alternativas: [
      "Paixão, justiça e caridade",
      "Coragem, perdão e gentileza",
      "Bondade, justiça e verdade",
      "Humildade, fortaleza e temor de Deus",
    ],
    correta: 2,
  },
  {
    id: 'efesios-44',
    secao: 'efesios',
    pergunta: "Paulo pede aos Efésios para que criem seus filhos na:",
    alternativas: [
      "Educação e doutrina do Senhor",
      "Honestidade e mansidão",
      "Fé e bondade",
      "Humildade e servidão do Senhor",
    ],
    correta: 0,
  },
  {
    id: 'efesios-45',
    secao: 'efesios',
    pergunta: "Como Paulo pede que os maridos amem suas esposas?",
    alternativas: [
      "Como Cristo amou seus discípulos",
      "Como Deus amou seu Filho",
      "Como um filho ama sua mãe",
      "Como Cristo amou a Igreja",
    ],
    correta: 3,
  },
  {
    id: 'efesios-46',
    secao: 'efesios',
    pergunta: "Qual era o nome do amigo de Paulo citado no final da carta?",
    alternativas: [
      "Barnabé",
      "Timóteo",
      "Tíquico",
      "Tito",
    ],
    correta: 2,
  },
  {
    id: 'efesios-47',
    secao: 'efesios',
    pergunta: "Qual o maior versículo de Efésios?",
    alternativas: [
      "6, 23",
      "5, 33",
      "4, 26",
      "7, 35",
    ],
    correta: 1,
  },
  {
    id: 'efesios-48',
    secao: 'efesios',
    pergunta: "Qual o menor versículo de Efésios?",
    alternativas: [
      "2, 15",
      "6,12",
      "3,20",
      "4,17",
    ],
    correta: 2,
  },
  {
    id: 'efesios-49',
    secao: 'efesios',
    pergunta: "Qual o livro anterior a Efésios?",
    alternativas: [
      "Romanos",
      "II Coríntios",
      "Gálatas",
      "João",
    ],
    correta: 2,
  },
  {
    id: 'efesios-50',
    secao: 'efesios',
    pergunta: "Qual o livro subsequente a Efésios?",
    alternativas: [
      "Filipenses",
      "Filemon",
      "I Tessalonicenses",
      "Tito",
    ],
    correta: 0,
  },
  {
    id: 'gerais-26',
    secao: 'gerais',
    pergunta: "Na História dos Papas, qual pontífice teve o papado mais curto da história (reconhecido oficialmente), governando por apenas 13 dias no ano de 1590 antes de falecer de malária?",
    alternativas: [
      "Papa João Paulo I",
      "Papa Leão XI",
      "Papa Celestino IV",
      "Papa Urbano VII",
    ],
    correta: 3,
  },
  {
    id: 'gerais-27',
    secao: 'gerais',
    pergunta: "Durante o período patrístico, qual santo africano e Doutor da Igreja ficou conhecido como o \"Pai da Ortodoxia\" por sua defesa da divindade de Cristo contra a heresia de Ário no século IV?",
    alternativas: [
      "Santo Agostinho de Hipona",
      "Santo Atanásio de Alexandria",
      "São Cipriano de Cartago",
      "São Cirilo de Jerusalém",
    ],
    correta: 1,
  },
  {
    id: 'gerais-28',
    secao: 'gerais',
    pergunta: "Através de qual Bula Papal, promulgada no ano de 1854, o Papa Pio IX definiu solenemente o Dogma da Imaculada Conceição da Santíssima Virgem Maria?",
    alternativas: [
      "Munificentissimus Deus",
      "Ineffabilis Deus",
      "Exsurge Domine",
      "Unam Sanctam",
    ],
    correta: 1,
  },
  {
    id: 'gerais-29',
    secao: 'gerais',
    pergunta: "Na teologia católica, a virtude moral que \"modera a atração pelos prazeres e procura o equilíbrio no uso dos bens criados\", sendo uma das quatro virtudes cardeais, é chamada de:",
    alternativas: [
      "Fortaleza",
      "Prudência",
      "Justiça",
      "Temperança",
    ],
    correta: 3,
  },
  {
    id: 'gerais-30',
    secao: 'gerais',
    pergunta: "Qual foi a Santa, autora do livro de visões \"Scivias\", foi declarada Doutora da Igreja pelo Papa Bento XVI em 2012?",
    alternativas: [
      "Santa Catarina de Sena",
      "Santa Teresa de Ávila",
      "Santa Hildegarda de Bingen",
      "Santa Gertrudes, a Grande",
    ],
    correta: 2,
  },
  {
    id: 'gerais-31',
    secao: 'gerais',
    pergunta: "No Livro do Apocalipse, o Cristo glorioso dita sete cartas às igrejas da Ásia. Qual dessas igrejas recebe a carta onde é duramente repreendida por não ser \"nem fria nem quente\", mas sim \"morna\"?",
    alternativas: [
      "Igreja de Éfeso",
      "Igreja de Tiatira",
      "Igreja de Pérgamo",
      "Igreja de Laodiceia",
    ],
    correta: 3,
  },
  {
    id: 'gerais-32',
    secao: 'gerais',
    pergunta: "A Liturgia da Igreja prevê o uso da cor Rósea (Rosa) nos paramentos sagrados apenas em dois domingos específicos do ano litúrgico. Quais são eles?",
    alternativas: [
      "1o Domingo do Advento e Domingo de Ramos",
      "3o Domingo do Advento e 4o Domingo da Quaresma",
      "Domingo de Pentecostes e Domingo da Misericórdia",
      "2o Domingo da Quaresma e Domingo da Epifania",
    ],
    correta: 1,
  },
  {
    id: 'gerais-33',
    secao: 'gerais',
    pergunta: "Qual Papa publicou em 1891 a encíclica \"Rerum Novarum\", documento que é considerado o grande marco fundador da Doutrina Social da Igreja moderna?",
    alternativas: [
      "Papa Leão XIII",
      "Papa Pio X",
      "Papa Gregório XVI",
      "Papa Bento XV",
    ],
    correta: 0,
  },
  {
    id: 'gerais-34',
    secao: 'gerais',
    pergunta: "Qual ordem religiosa, caracterizada pelo rigoroso voto de silêncio, monges que vivem em celas solitárias e uma vida quase que totalmente eremítica em comunidade, foi fundada por São Bruno em 1084?",
    alternativas: [
      "Ordem de Cister",
      "Ordem dos Cartuxos",
      "Ordem dos Carmelitas Descalços",
      "Ordem dos Premonstratenses",
    ],
    correta: 1,
  },
  {
    id: 'gerais-35',
    secao: 'gerais',
    pergunta: "Quem foi o sucessor imediato de São Pedro no governo da Igreja de Roma, tornando-se o segundo Papa da história?",
    alternativas: [
      "Clemente",
      "Cleto",
      "Lino",
      "Sisto",
    ],
    correta: 2,
  },
  {
    id: 'gerais-36',
    secao: 'gerais',
    pergunta: "Qual livro do Novo Testamento contém apenas um único capítulo com 25 versículos e é uma carta pessoal de São Paulo sobre o escravo Onésimo?",
    alternativas: [
      "Tito",
      "Judas",
      "Filêmon",
      "2 João",
    ],
    correta: 2,
  },
  {
    id: 'gerais-37',
    secao: 'gerais',
    pergunta: "Qual dos doze apóstolos de Jesus é historicamente conhecido por ter levado o Evangelho até a Índia e lá sofrido o martírio?",
    alternativas: [
      "São Bartolomeu",
      "São Tomé",
      "São Simão",
      "São Matias",
    ],
    correta: 1,
  },
  {
    id: 'gerais-40',
    secao: 'gerais',
    pergunta: "Qual Papa do século XX foi responsável por convocar e abrir oficialmente o Concílio Ecumênico Vaticano II no ano de 1962?",
    alternativas: [
      "Papa Pio XII",
      "Papa João XXIII",
      "Papa Paulo VI",
      "Papa João Paulo I",
    ],
    correta: 1,
  },
  {
    id: 'gerais-41',
    secao: 'gerais',
    pergunta: "Quando foi realizada a Missa de dedicação da Igreja Matriz?",
    alternativas: [
      "13/12/2021",
      "24/11/2020",
      "13/12/2020",
      "14/12/2022",
    ],
    correta: 2,
  },
  {
    id: 'gerais-42',
    secao: 'gerais',
    pergunta: "Qual o nome do pároco anterior ao Frei Vilson Rech O.Carm?",
    alternativas: [
      "Edmilson Carvalho dos Santos",
      "Edmilson Borges Coelho",
      "Edmilson Borges de Carvalho",
      "Edmilson de Carvalho da Silva",
    ],
    correta: 2,
  },
  {
    id: 'gerais-43',
    secao: 'gerais',
    pergunta: "Quem foi responsável pelas visões da paixão de Cristo?",
    alternativas: [
      "Santa Faustina Kowalska",
      "Santa Paulina",
      "Beata Sandra Sabattini",
      "Beata Anna Catarina Emmerich",
    ],
    correta: 3,
  },
  {
    id: 'gerais-44',
    secao: 'gerais',
    pergunta: "Em que ano se iniciou o papado de São João Paulo II?",
    alternativas: [
      "1978",
      "1989",
      "1975",
      "1981",
    ],
    correta: 0,
  },
  {
    id: 'gerais-45',
    secao: 'gerais',
    pergunta: "Qual foi o primeiro Santo canonizado pelo Papa Francisco",
    alternativas: [
      "Josémaria Escriva",
      "Antônio Primaldo",
      "Irmã Dulce",
      "Catarina de Sena",
    ],
    correta: 1,
  },
  {
    id: 'gerais-46',
    secao: 'gerais',
    pergunta: "Em que ano São Padre Pio foi canonizado?",
    alternativas: [
      "1980",
      "1999",
      "2005",
      "2002",
    ],
    correta: 3,
  },
  {
    id: 'gerais-47',
    secao: 'gerais',
    pergunta: "Quantas partes possuí o Catecismo da Igreja Católica?",
    alternativas: [
      "2",
      "4",
      "5",
      "3",
    ],
    correta: 1,
  },
  {
    id: 'gerais-48',
    secao: 'gerais',
    pergunta: "Quando o ocorreu o milagre do sol em Fátima?",
    alternativas: [
      "1913",
      "1915",
      "1920",
      "1917",
    ],
    correta: 3,
  },
  {
    id: 'gerais-49',
    secao: 'gerais',
    pergunta: "O que é o CDC?",
    alternativas: [
      "conjunto de leis que organiza a Igreja Católica de rito latino",
      "conjunto de regras que organizou os livros presentes na bíblia",
      "conjunto de ritos aprovados pelos papas ao decorrer da história da Igreja",
      "conjunto de livros que descrevem a vida dos santos canonizados",
    ],
    correta: 0,
  },
  {
    id: 'gerais-50',
    secao: 'gerais',
    pergunta: "Onde nasceu o Papa Leão XIV?",
    alternativas: [
      "Pittsburg, Estados Unidos",
      "Atlanta, Estados Unidos",
      "Chicago, Estados Unidos",
      "Los Angeles, Estados Unidos",
    ],
    correta: 2,
  },
  // fonte: Doutrina/CIC 1113
  {
    id: 'gerais-51',
    secao: 'gerais',
    pergunta: "Quantos sacramentos existem na Igreja Católica?",
    alternativas: [
      "5",
      "6",
      "7",
      "9",
    ],
    correta: 2,
  },
  // fonte: CIC 1212
  {
    id: 'gerais-52',
    secao: 'gerais',
    pergunta: "Quais são os sacramentos de iniciação cristã?",
    alternativas: [
      "Batismo, Confirmação e Eucaristia",
      "Batismo, Penitência e Eucaristia",
      "Confirmação, Eucaristia e Unção dos Enfermos",
      "Batismo, Ordem e Matrimônio",
    ],
    correta: 0,
  },
  // fonte: CIC 1420-1532
  {
    id: 'gerais-53',
    secao: 'gerais',
    pergunta: "Quais são os sacramentos de cura, segundo a classificação da Igreja?",
    alternativas: [
      "Batismo e Confirmação",
      "Penitência e Unção dos Enfermos",
      "Ordem e Matrimônio",
      "Eucaristia e Penitência",
    ],
    correta: 1,
  },
  // fonte: Dogma da Santíssima Trindade
  {
    id: 'gerais-54',
    secao: 'gerais',
    pergunta: "Quantas pessoas há na Santíssima Trindade?",
    alternativas: [
      "1",
      "2",
      "3",
      "4",
    ],
    correta: 2,
  },
  // fonte: 1Cor 13,13 / CIC 1812-1829
  {
    id: 'gerais-55',
    secao: 'gerais',
    pergunta: "Quais são as três virtudes teologais?",
    alternativas: [
      "Prudência, Justiça e Fortaleza",
      "Fé, Esperança e Caridade",
      "Sabedoria, Ciência e Piedade",
      "Humildade, Paciência e Mansidão",
    ],
    correta: 1,
  },
  // fonte: CIC 1805
  {
    id: 'gerais-56',
    secao: 'gerais',
    pergunta: "Quantas virtudes cardeais existem?",
    alternativas: [
      "3",
      "4",
      "5",
      "7",
    ],
    correta: 1,
  },
  // fonte: Is 11,2-3 / CIC 1831
  {
    id: 'gerais-57',
    secao: 'gerais',
    pergunta: "Quantos dons do Espírito Santo a tradição da Igreja reconhece?",
    alternativas: [
      "5",
      "6",
      "7",
      "9",
    ],
    correta: 2,
  },
  // fonte: ordem canônica da Bíblia
  {
    id: 'gerais-58',
    secao: 'gerais',
    pergunta: "Qual é o primeiro livro da Bíblia?",
    alternativas: [
      "Êxodo",
      "Gênesis",
      "Levítico",
      "Números",
    ],
    correta: 1,
  },
  // fonte: ordem canônica da Bíblia
  {
    id: 'gerais-59',
    secao: 'gerais',
    pergunta: "Qual é o último livro da Bíblia?",
    alternativas: [
      "Apocalipse",
      "Judas",
      "3ª João",
      "Hebreus",
    ],
    correta: 0,
  },
  // fonte: canon catolico (46 AT + 27 NT)
  {
    id: 'gerais-60',
    secao: 'gerais',
    pergunta: "Quantos livros ao todo tem a Bíblia Católica (Antigo e Novo Testamento juntos)?",
    alternativas: [
      "66",
      "27",
      "73",
      "46",
    ],
    correta: 2,
  },
  // fonte: canon do Novo Testamento
  {
    id: 'gerais-61',
    secao: 'gerais',
    pergunta: "Quantos evangelhos há no Novo Testamento, e quais são?",
    alternativas: [
      "3: Mateus, Marcos e Lucas",
      "4: Mateus, Marcos, Lucas e João",
      "4: Mateus, Marcos, João e Paulo",
      "5: Mateus, Marcos, Lucas, João e Atos",
    ],
    correta: 1,
  },
  // fonte: Mt 6,9-13 / Lc 11,1-4
  {
    id: 'gerais-62',
    secao: 'gerais',
    pergunta: "Qual oração o próprio Jesus ensinou aos discípulos, quando pediram \"Senhor, ensina-nos a rezar\"?",
    alternativas: [
      "Ave Maria",
      "Pai Nosso",
      "Credo",
      "Glória ao Pai",
    ],
    correta: 1,
  },
  // fonte: calendário litúrgico, 16 de julho
  {
    id: 'gerais-64',
    secao: 'gerais',
    pergunta: "Em que dia a Igreja celebra Nossa Senhora do Carmo?",
    alternativas: [
      "15 de agosto",
      "16 de julho",
      "8 de dezembro",
      "11 de fevereiro",
    ],
    correta: 1,
  },
  // fonte: autoria tradicional
  {
    id: 'efesios-51',
    secao: 'efesios',
    pergunta: "Quem é o autor tradicional da Carta aos Efésios?",
    alternativas: [
      "São Pedro",
      "São João",
      "São Paulo",
      "São Tiago",
    ],
    correta: 2,
  },
  // fonte: cartas do cativeiro
  {
    id: 'efesios-52',
    secao: 'efesios',
    pergunta: "De qual cidade Paulo escreveu a Carta aos Efésios, durante seu cativeiro?",
    alternativas: [
      "Éfeso",
      "Roma",
      "Corinto",
      "Atenas",
    ],
    correta: 1,
  },
  // fonte: estrutura do livro
  {
    id: 'efesios-53',
    secao: 'efesios',
    pergunta: "Quantos capítulos tem a Carta aos Efésios?",
    alternativas: [
      "4",
      "5",
      "6",
      "8",
    ],
    correta: 2,
  },
  // fonte: Ef 6,12
  {
    id: 'efesios-54',
    secao: 'efesios',
    pergunta: "Em Efésios 6,12, contra o que Paulo diz que a nossa luta NÃO é?",
    alternativas: [
      "Contra o pecado",
      "Contra a carne e o sangue",
      "Contra o mundo",
      "Contra as tentações",
    ],
    correta: 1,
  },
  // fonte: estrutura do livro
  {
    id: 'tobias-51',
    secao: 'tobias',
    pergunta: "Quantos capítulos tem o livro de Tobias?",
    alternativas: [
      "10",
      "12",
      "14",
      "16",
    ],
    correta: 2,
  },
  // fonte: Tb 12,15 e tradição
  {
    id: 'tobias-52',
    secao: 'tobias',
    pergunta: "Quais são os três arcanjos mencionados pelo nome nas Escrituras reconhecidas pela Igreja Católica?",
    alternativas: [
      "Miguel, Gabriel e Rafael",
      "Miguel, Uriel e Rafael",
      "Gabriel, Rafael e Sealtiel",
      "Miguel, Gabriel e Uriel",
    ],
    correta: 0,
  },
  // fonte: classificação da Bíblia Ave Maria
  {
    id: 'tobias-53',
    secao: 'tobias',
    pergunta: "O livro de Tobias é classificado, junto com Judite e Ester, em qual grupo de livros do Antigo Testamento?",
    alternativas: [
      "Livros Proféticos",
      "Livros Sapienciais",
      "Livros Históricos",
      "Livros Poéticos",
    ],
    correta: 2,
  },
  // fonte: Jo 1,1
  {
    id: 'joao-51',
    secao: 'joao',
    pergunta: "Com qual frase inicia o prólogo do Evangelho de João, uma clara referência ao início do livro de Gênesis?",
    alternativas: [
      "\"No princípio Deus criou os céus e a terra\"",
      "\"No princípio era o Verbo\"",
      "\"No princípio havia luz\"",
      "\"No princípio Deus falou ao mundo\"",
    ],
    correta: 1,
  },
  // fonte: Jo 14,6
  {
    id: 'joao-52',
    secao: 'joao',
    pergunta: "Em João 14,6, Jesus se declara \"o caminho, a...\", completando com quais duas palavras?",
    alternativas: [
      "A luz e a paz",
      "A verdade e a vida",
      "A porta e o pastor",
      "A videira e o pão",
    ],
    correta: 1,
  },
  // fonte: Jo 20,24-29
  {
    id: 'joao-53',
    secao: 'joao',
    pergunta: "No Evangelho de João, qual discípulo só creu na ressurreição de Jesus depois de tocar suas feridas?",
    alternativas: [
      "Pedro",
      "André",
      "Tomé",
      "Filipe",
    ],
    correta: 2,
  },
  // fonte: Jo 11
  {
    id: 'joao-54',
    secao: 'joao',
    pergunta: "Quem Jesus ressuscitou dentre os mortos em Betânia, depois de já estar sepultado há quatro dias?",
    alternativas: [
      "O filho da viúva de Naim",
      "A filha de Jairo",
      "Lázaro",
      "O jovem de Naim",
    ],
    correta: 2,
  },
  // fonte: Jo 2,1-11
  {
    id: 'joao-55',
    secao: 'joao',
    pergunta: "Em qual cidade Jesus realizou seu primeiro milagre, transformando água em vinho?",
    alternativas: [
      "Nazaré",
      "Cafarnaum",
      "Caná",
      "Betânia",
    ],
    correta: 2,
  },
  // fonte: Jo 21,20 e tradição
  {
    id: 'joao-56',
    secao: 'joao',
    pergunta: "Como é chamado, no próprio texto do Evangelho, o discípulo tradicionalmente identificado como autor do quarto evangelho?",
    alternativas: [
      "O discípulo fiel",
      "O discípulo amado",
      "O discípulo zeloso",
      "O discípulo primeiro",
    ],
    correta: 1,
  },
];
