// EJAC — GBJ, Quiz: perguntas gerais e dos livros pré-selecionados
// (Tobias, Evangelho de João, Efésios), extraídas do documento oficial
// "PERGUNTAS - JUREF - GBJ - 2026". Cada pergunta tem um id estável
// (secao-numero) usado pra registrar contestação, então não muda a ordem
// nem os ids depois de publicado — só adicione no fim se quiser crescer o banco.
export const SECOES_QUIZ = {
  joao: 'Evangelho de João',
  tobias: 'Tobias',
  efesios: 'Efésios',
  gerais: 'Perguntas gerais',
};

export const PERGUNTAS_QUIZ = [
  {
    id: 'joao-1',
    secao: 'joao',
    pergunta: "QUANDO JOÃO BATISTA COMEÇOU A PREGAÇÃO QUEM OS JUDEUS ESTAVAM ESPERANDO? (JO 1,19-28)",
    alternativas: [
      "ELIAS",
      "O MESSIAS",
      "PROFETA",
      "JOÃO",
    ],
    correta: 1,
  },
  {
    id: 'joao-2',
    secao: 'joao',
    pergunta: "QUEM FOI ENVIADO POR DEUS PARA DAR TESTEMUNHO DE LUZ? (JO 1, 06-08)",
    alternativas: [
      "JOÃO",
      "PAULO",
      "PEDRO",
      "LUCAS",
    ],
    correta: 0,
  },
  {
    id: 'joao-3',
    secao: 'joao',
    pergunta: "SEGUNDO JOÃO COMO TERMINA A PRIMEIRA SEMANA DE JESUS? (JO 2, 01-12)",
    alternativas: [
      "CHAMANDO NATANAEL",
      "ENCONTRO DE JESUS E JOÃO",
      "BATISMO DE JESUS NAS ÁGUAS",
      "COM A FESTA DE CASAMENTO EM CANÁ",
    ],
    correta: 3,
  },
  {
    id: 'joao-4',
    secao: 'joao',
    pergunta: "QUANTAS JARRAS DE PEDRA TINHA NA FESTA DE CANA? (JO 2, 06)",
    alternativas: [
      "6",
      "7",
      "8",
      "9",
    ],
    correta: 0,
  },
  {
    id: 'joao-5',
    secao: 'joao',
    pergunta: "ONDE JESUS ESTAVA DURANTE A FESTA DA PÁSCOA? (JO 2, 23)",
    alternativas: [
      "NO SEPULCRO",
      "BELÉM",
      "TEMPLO",
      "JERUSALEM",
    ],
    correta: 3,
  },
  {
    id: 'joao-6',
    secao: 'joao',
    pergunta: "QUEM FOI PROCURAR JESUS DE NOITE PARA CONVERSAR? (JO 3, 01-02)",
    alternativas: [
      "HERÓDES",
      "JUDAS",
      "NICODEMOS",
      "PEDRO",
    ],
    correta: 2,
  },
  {
    id: 'joao-7',
    secao: 'joao',
    pergunta: "QUANTOS MARIDOS TEVE A SAMARITANA SEGUNDO JESUS? (JO 4, 16-18)",
    alternativas: [
      "2",
      "3",
      "4",
      "5",
    ],
    correta: 3,
  },
  {
    id: 'joao-8',
    secao: 'joao',
    pergunta: "O QUE JESUS DISSE SOBRE QUEM VEM A ELE? (JO 6, 37)",
    alternativas: [
      "VIDA ETERNA",
      "NUNCA SERÁ REJEITADO",
      "EU LHE DAREI DESCANSO",
      "BOM ÂNIMO",
    ],
    correta: 1,
  },
  {
    id: 'joao-9',
    secao: 'joao',
    pergunta: "ONDE JESUS EVITAVA ANDAR? (JO 7, 01)",
    alternativas: [
      "GALILEIA",
      "JERUSALÉM",
      "SAMARIA",
      "JUDEIA",
    ],
    correta: 3,
  },
  {
    id: 'joao-10',
    secao: 'joao',
    pergunta: "POR QUE JESUS EVITAVA ANDAR PELA JUDEIA? (JO 7, 01)",
    alternativas: [
      "POIS O POVO DE LÁ ERA IMPURO",
      "POIS O POVO DE LÁ QUERIA MATA-LÓ",
      "POIS O POVO NÃO ACEITAVA SUAS PREGAÇÕES",
      "POIS QUEM CUIDAVA DESSA REGIÃO ERAM OS APÓSTOLOS",
    ],
    correta: 1,
  },
  {
    id: 'joao-11',
    secao: 'joao',
    pergunta: "DE QUAL POVOADO LÁZARO ERA NATURAL? (JO 11, 01)",
    alternativas: [
      "JERUSALÉM",
      "GALILEIA",
      "BETÂNIA",
      "BABILÔNIA",
    ],
    correta: 2,
  },
  {
    id: 'joao-12',
    secao: 'joao',
    pergunta: "QUANTOS DIAS ANTES DA PÁSCOA JESUS FOI PARA BETÂNIA? (JO 12, 01)",
    alternativas: [
      "5 DIAS",
      "6 DIAS",
      "7 DIAS",
      "8 DIAS",
    ],
    correta: 1,
  },
  {
    id: 'joao-13',
    secao: 'joao',
    pergunta: "COM O QUE MARIA ENXUGOU OS PÉS UNGIDOS DE JESUS? (JO 12, 03)",
    alternativas: [
      "COM UM PANO",
      "COM UMA TOALHA",
      "COM AS VESTES",
      "COM SEU CABELO",
    ],
    correta: 3,
  },
  {
    id: 'joao-14',
    secao: 'joao',
    pergunta: "O QUE JESUS NOS DÁ? (JO 14, 27)",
    alternativas: [
      "SALVAÇÃO",
      "CURA",
      "PAZ",
      "PERDÃO",
    ],
    correta: 2,
  },
  {
    id: 'joao-15',
    secao: 'joao',
    pergunta: "QUAL O ADVOGADO QUE JESUS MANDA DE JUNTO DO PAI? (JO 15, 26)",
    alternativas: [
      "ESPÍRITO DA VERDADE",
      "ESPÍRITO SANTO",
      "VIRGEM MARIA",
      "DISCÍPULO JOÃO",
    ],
    correta: 0,
  },
  {
    id: 'joao-16',
    secao: 'joao',
    pergunta: "O QUE ACONTECE COM QUEM NÃO PERMANECE EM CRISTO? (JO 15, 06)",
    alternativas: [
      "NÃO PERTENCERÁ AO REINO DOS CÉUS",
      "SERÁ PERDOADO",
      "NÃO SERÁ PERDOADO",
      "SERÁ JOGADO FORA",
    ],
    correta: 3,
  },
  {
    id: 'joao-17',
    secao: 'joao',
    pergunta: "QUEM COLOCOU AS MÃOS NAS FERIDAS DE JESUS POIS NÃO ACREDITAVA NA RESSURREIÇÃO? (JO 20,24-29)",
    alternativas: [
      "PEDRO",
      "TOMÉ",
      "PAULO",
      "ZACARIAS",
    ],
    correta: 1,
  },
  {
    id: 'joao-18',
    secao: 'joao',
    pergunta: "QUAL O NOME DO LUGAR EM QUE JESUS FOI CRUCIFICADO? (JO 19,17)",
    alternativas: [
      "SEPULCRO",
      "HORTO DAS OLIVEIRAS",
      "LUGAR DA CAVEIRA",
      "LUGAR DA MORTE",
    ],
    correta: 2,
  },
  {
    id: 'joao-19',
    secao: 'joao',
    pergunta: "O QUE PILATOS MANDOU ESCREVER NA CRUZ DE JESUS? (JO 19, 19)",
    alternativas: [
      "EU SOU O REI DOS JUDEUS",
      "O FILHO DE DEUS",
      "REI DOS JUDEUS",
      "JESUS NAZARENO O REI DOS JUDEUS",
    ],
    correta: 3,
  },
  {
    id: 'joao-20',
    secao: 'joao',
    pergunta: "EM QUANTAS PARTES FORAM REPARTIDAS AS VESTES DE JESUS? (JO 19, 23)",
    alternativas: [
      "DUAS",
      "TRÊS",
      "QUATRO",
      "CINCO",
    ],
    correta: 2,
  },
  {
    id: 'joao-21',
    secao: 'joao',
    pergunta: "QUEM ESTAVA JUNTO A JESUS NA CRUZ? (JO 19, 25)",
    alternativas: [
      "SUA MÃE, MARIA MADALENA, MARIA DE CLÉOFAS",
      "SUA MÃE e MARIA MADALENA",
      "SUA MÃE, MARIA MADALENA e JOÃO",
      "SUA MÃE, MARIA DE CLÉOFAS e JOÃO",
    ],
    correta: 0,
  },
  {
    id: 'joao-22',
    secao: 'joao',
    pergunta: "A QUEM SE REFERE A SEGUINTE FRASE: ”EU DISSE ESSAS COISAS PARA QUE VOCÊS TENHAM MINHA PAZ. NESTE MUNDO VOCÊS TERÃO AFLIÇÕES, MAS TENHAM CORAGEM; EU VENCI O MUNDO. “ (JO 16, 33)",
    alternativas: [
      "AOS GALILEUS",
      "AOS DISCÍPULOS",
      "AOS PAGÃOS",
      "AOS JUDEUS",
    ],
    correta: 1,
  },
  {
    id: 'joao-23',
    secao: 'joao',
    pergunta: "QUEM DISSE A JESUS: A QUEM IREMOS, SENHOR? TU TENS PALAVRAS DE VIDA ETERNA. (JO 6, 68)",
    alternativas: [
      "JOÃO",
      "JUDAS",
      "TOMÉ",
      "PEDRO",
    ],
    correta: 3,
  },
  {
    id: 'joao-24',
    secao: 'joao',
    pergunta: "O QUE JESUS OFERECEU PARA MULHER SAMARITANA? (JO 4, 07-14)",
    alternativas: [
      "PÃO",
      "PEIXES",
      "ÁGUA",
      "ÓLEO DA UNÇÃO",
    ],
    correta: 2,
  },
  {
    id: 'joao-25',
    secao: 'joao',
    pergunta: "QUANTOS PÃES E PEIXES HAVIAM QUANDO JESUS ALIMENTOU A MULTIDÃO? (JO 6, 08)",
    alternativas: [
      "3 PÃES & 2 PEIXES",
      "4 PÃES & 2 PEIXES",
      "5 PÃES & 3 PEIXES",
      "5 PÃES & 2 PEIXES PERGUNTAS DE TOBIAS",
    ],
    correta: 3,
  },
  {
    id: 'tobias-1',
    secao: 'tobias',
    pergunta: "DE QUAL TRIBO DE ISRAEL TOBIT ERA DESCENDENTE? (TB 1,1-4)",
    alternativas: [
      "JUDÁ",
      "LEVI",
      "NEFTALI",
      "BENJAMIM",
    ],
    correta: 2,
  },
  {
    id: 'tobias-2',
    secao: 'tobias',
    pergunta: "PARA QUAL CIDADE TOBIT FOI LEVADO COMO EXILADO? (TB 1,2-3)",
    alternativas: [
      "JERUSALÉM",
      "NÍNIVE",
      "BELÉM",
      "RAGES",
    ],
    correta: 1,
  },
  {
    id: 'tobias-3',
    secao: 'tobias',
    pergunta: "O QUE TOBIT COSTUMAVA FAZER PELOS SEUS COMPATRIOTAS NECESSITADOS? (TB 1,16-18)",
    alternativas: [
      "COBRAR IMPOSTOS DELES",
      "DAR-LHES ALIMENTOS, ROUPAS E SEPULTAR OS MORTOS",
      "LEVÁ-LOS PARA JERUSALÉM",
      "TRABALHAR NO PALÁCIO DO REI POR ELES",
    ],
    correta: 1,
  },
  {
    id: 'tobias-4',
    secao: 'tobias',
    pergunta: "O QUE ACONTECEU COM TOBIT ENQUANTO DORMIA NO PÁTIO DE SUA CASA? (TB 2,9-10)",
    alternativas: [
      "FOI ATACADO POR UM ANIMAL",
      "FOI ROUBADO",
      "CAIU SOBRE ELE UMA ÁRVORE",
      "EXCREMENTOS DE PARDAIS CAÍRAM EM SEUS OLHOS, CAUSANDO SUA CEGUEIRA",
    ],
    correta: 3,
  },
  {
    id: 'tobias-5',
    secao: 'tobias',
    pergunta: "QUAL ERA O NOME DA ESPOSA DE TOBIT? (TB 1,9; 2,11-14)",
    alternativas: [
      "SARA",
      "EDNA",
      "ANA",
      "DÉBORA",
    ],
    correta: 2,
  },
  {
    id: 'tobias-6',
    secao: 'tobias',
    pergunta: "O QUE ANA RECEBEU COMO PAGAMENTO ALÉM DO DINHEIRO PELO TRABALHO QUE REALIZOU? (TB 2,11-13)",
    alternativas: [
      "UMA OVELHA",
      "UM CABRITO",
      "UM CORDEIRO",
      "UM BOI",
    ],
    correta: 1,
  },
  {
    id: 'tobias-7',
    secao: 'tobias',
    pergunta: "QUEM TAMBÉM REZOU A DEUS EM MEIO AO SOFRIMENTO NO MESMO DIA EM QUE TOBIT REZOU? (TB 3,7-10)",
    alternativas: [
      "EDNA",
      "ANA",
      "SARA",
      "DÉBORA",
    ],
    correta: 2,
  },
  {
    id: 'tobias-8',
    secao: 'tobias',
    pergunta: "QUANTOS HOMENS JÁ HAVIAM SIDO DADOS EM CASAMENTO A SARA ANTES DE TOBIAS? (TB 3,8; 6,14)",
    alternativas: [
      "CINCO",
      "SEIS",
      "SETE",
      "OITO",
    ],
    correta: 2,
  },
  {
    id: 'tobias-9',
    secao: 'tobias',
    pergunta: "QUE CONSELHO TOBIT DEU A TOBIAS A RESPEITO DE SUA MÃE? (TB 4,3-4)",
    alternativas: [
      "QUE A DEIXASSE MORAR SOZINHA",
      "QUE A HONRASSE E NUNCA A ABANDONASSE ENQUANTO ELA VIVESSE",
      "QUE A ENVIASSE PARA JERUSALÉM",
      "QUE LHE ENTREGASSE TODO O DINHEIRO",
    ],
    correta: 1,
  },
  {
    id: 'tobias-10',
    secao: 'tobias',
    pergunta: "O QUE TOBIT ACONSELHOU TOBIAS A FAZER QUANDO ENCONTRASSE UMA PESSOA POBRE? (TB 4,7-11)",
    alternativas: [
      "IGNORÁ-LA",
      "PEDIR QUE TRABALHASSE EM SUA CASA",
      "DAR ESMOLA CONFORME OS BENS QUE POSSUÍSSE",
      "MANDÁ-LA PROCURAR O REI",
    ],
    correta: 2,
  },
  {
    id: 'tobias-11',
    secao: 'tobias',
    pergunta: "QUAL PRINCÍPIO TOBIT ENSINOU A TOBIAS SOBRE O MODO DE TRATAR OS OUTROS? (TB 4,15)",
    alternativas: [
      "FAZER AOS OUTROS AQUILO QUE ELES FIZEREM PRIMEIRO",
      "NÃO FAZER A NINGUÉM AQUILO QUE NÃO GOSTARIA QUE FIZESSEM A ELE",
      "SEMPRE COLOCAR A PRÓPRIA VONTADE EM PRIMEIRO LUGAR",
      "NUNCA CONFIAR EM NINGUÉM",
    ],
    correta: 1,
  },
  {
    id: 'tobias-12',
    secao: 'tobias',
    pergunta: "QUANTO DINHEIRO TOBIT HAVIA DEIXADO EM DEPÓSITO COM GABAEL? (TB 4,20)",
    alternativas: [
      "CEM QUILOS DE PRATA",
      "DUZENTOS QUILOS DE PRATA",
      "TREZENTOS QUILOS DE PRATA",
      "QUINHENTOS QUILOS DE PRATA",
    ],
    correta: 2,
  },
  {
    id: 'tobias-13',
    secao: 'tobias',
    pergunta: "QUEM TOBIAS ENCONTROU QUANDO SAIU À PROCURA DE ALGUÉM PARA ACOMPANHÁ-LO ATÉ A MÉDIA? (TB 5,4-6)",
    alternativas: [
      "GABAEL",
      "RAFAEL, QUE SE APRESENTOU COMO AZARIAS",
      "RAGÜEL",
      "AICAR",
    ],
    correta: 1,
  },
  {
    id: 'tobias-14',
    secao: 'tobias',
    pergunta: "QUAL ANIMAL ACOMPANHOU TOBIAS E RAFAEL DURANTE A VIAGEM? (TB 6,1)",
    alternativas: [
      "UM CAVALO",
      "UM JUMENTO",
      "UM CACHORRO",
      "UM CAMELO",
    ],
    correta: 2,
  },
  {
    id: 'tobias-15',
    secao: 'tobias',
    pergunta: "O QUE TOBIAS ENCONTROU QUANDO ESTAVA LAVANDO OS PÉS NO RIO TIGRE? (TB 6,2-4)",
    alternativas: [
      "UMA SERPENTE",
      "UM GRANDE PEIXE",
      "UMA MOEDA",
      "UMA PEDRA PRECIOSA",
    ],
    correta: 1,
  },
  {
    id: 'tobias-16',
    secao: 'tobias',
    pergunta: "QUAIS PARTES DO PEIXE RAFAEL MANDOU TOBIAS GUARDAR? (TB 6,4-5)",
    alternativas: [
      "A CABEÇA, AS ESCAMAS E AS NADADEIRAS",
      "O SANGUE, OS OLHOS E OS OSSOS",
      "O FEL, O CORAÇÃO E O FÍGADO",
      "A PELE, AS ESCAMAS E O CORAÇÃO",
    ],
    correta: 2,
  },
  {
    id: 'tobias-17',
    secao: 'tobias',
    pergunta: "O QUE RAFAEL ACONSELHOU TOBIAS E SARA A FAZER ANTES DE SE UNIREM COMO MARIDO E MULHER? (TB 6,17-18)",
    alternativas: [
      "FAZER UMA VIAGEM",
      "OFERECER UM SACRIFÍCIO NO TEMPLO",
      "LEVANTAR-SE E REZAR, PEDINDO A MISERICÓRDIA E A PROTEÇÃO DO SENHOR",
      "ESPERAR SETE DIAS SEM CONVERSAR",
    ],
    correta: 2,
  },
  {
    id: 'tobias-18',
    secao: 'tobias',
    pergunta: "DE ACORDO COM O RELATO, O QUE ACONTECEU QUANDO TOBIAS COLOCOU O CORAÇÃO E O FÍGADO DO PEIXE NO QUEIMADOR DE INCENSO? (TB 8,2-3)",
    alternativas: [
      "O PEIXE VOLTOU À VIDA",
      "O DEMÔNIO FUGIU",
      "TOBIAS PERDEU A VISÃO",
      "SARA FICOU DOENTE",
    ],
    correta: 1,
  },
  {
    id: 'tobias-19',
    secao: 'tobias',
    pergunta: "O QUE TOBIAS E SARA FIZERAM JUNTOS DURANTE A NOITE DE NÚPCIAS? (TB 8,4-8)",
    alternativas: [
      "DORMIRAM IMEDIATAMENTE SEM CONVERSAR",
      "SAÍRAM DA CASA DE RAGÜEL",
      "REZARAM E PEDIRAM A PROTEÇÃO E A MISERICÓRDIA DE DEUS",
      "FORAM PROCURAR GABAEL",
    ],
    correta: 2,
  },
  {
    id: 'tobias-20',
    secao: 'tobias',
    pergunta: "COMO TOBIT RECUPEROU A VISÃO? (TB 11,7-13)",
    alternativas: [
      "PELA ORAÇÃO DE ANA",
      "POR MEIO DO FEL DO PEIXE APLICADO AOS SEUS OLHOS",
      "POR MEIO DE UMA CIRURGIA",
      "PELA IMPOSIÇÃO DAS MÃOS DE RAGÜEL",
    ],
    correta: 1,
  },
  {
    id: 'tobias-21',
    secao: 'tobias',
    pergunta: "QUEM REVELOU FINALMENTE SUA VERDADEIRA IDENTIDADE A TOBIT E TOBIAS? (TB 12,11-15)",
    alternativas: [
      "GABAEL",
      "RAGÜEL",
      "RAFAEL",
      "AICAR",
    ],
    correta: 2,
  },
  {
    id: 'tobias-22',
    secao: 'tobias',
    pergunta: "COM QUE IDADE TOBIT MORREU? (TB 14,1-2)",
    alternativas: [
      "100 ANOS",
      "105 ANOS",
      "112 ANOS",
      "120 ANOS",
    ],
    correta: 2,
  },
  {
    id: 'tobias-23',
    secao: 'tobias',
    pergunta: "POR QUE TOBIAS DECIDIU ACOMPANHAR O ANJO RAFAEL EM SUA VIAGEM? (TB 5,1-3)",
    alternativas: [
      "PARA VISITAR JERUSALÉM",
      "PARA RECUPERAR O DINHEIRO QUE TOBIT HAVIA DEIXADO COM GABAEL",
      "PARA PROCURAR UM EMPREGO NA MÉDIA",
      "PARA VISITAR RAGÜEL",
    ],
    correta: 1,
  },
  {
    id: 'tobias-24',
    secao: 'tobias',
    pergunta: "QUAL ERA O NOME DO PAI DE SARA? (TB 3,7; 6,9-12)",
    alternativas: [
      "TOBIT",
      "GABAEL",
      "RAGÜEL",
      "AICAR",
    ],
    correta: 2,
  },
  {
    id: 'tobias-25',
    secao: 'tobias',
    pergunta: "O QUE RAGÜEL FEZ QUANDO SOUBE QUE TOBIAS HAVIA CHEGADO À SUA CASA? (TB 7,1-6)",
    alternativas: [
      "MANDOU TOBIAS EMBORA",
      "RECEBEU TOBIAS COM ALEGRIA E O ACOLHEU",
      "PEDIU QUE TOBIAS VOLTASSE PARA NÍNIVE",
      "ENVIOU TOBIAS IMEDIATAMENTE A GABAE PERGUNTAS DE EFÉSIOS",
    ],
    correta: 1,
  },
  {
    id: 'efesios-1',
    secao: 'efesios',
    pergunta: "QUAL DAS CARTAS ABAIXO NÃO É UMA CARTA ESCRITA EM CATIVEIRO? (INTRODUÇÃO DO TEXTO)",
    alternativas: [
      "COLOSSENSES",
      "GÁLATAS",
      "FILIPENSES",
      "FELIMÔN",
    ],
    correta: 1,
  },
  {
    id: 'efesios-2',
    secao: 'efesios',
    pergunta: "SEGUNDO A INTRODUÇÃO DO TEXTO QUEM PROVAVELMENTE ESCREVEU A CARTA AOS EFÉSIOS? (INTRODUÇÃO DO TEXTO)",
    alternativas: [
      "LUCAS",
      "TÍQUICO",
      "UM DISCÍPULO DE PAULO",
      "O PRÓPRIO PAULO",
    ],
    correta: 2,
  },
  {
    id: 'efesios-3',
    secao: 'efesios',
    pergunta: "NA INTRODUÇÃO, O TEXTO APRESENTA A REGIÃO ONDE O AUTOR DO LIVRO MORAVA, QUE REGIÃO ERA ESSA? (INTRODUÇÃO DO TEXTO)",
    alternativas: [
      "LISTRA",
      "ANTIOQUIA",
      "CESARÉIA DE FILIPO",
      "VALE DO RIO LICO",
    ],
    correta: 3,
  },
  {
    id: 'efesios-4',
    secao: 'efesios',
    pergunta: "A CARTA AOS EFÉSIOS TRAZ PROBLEMAS GERAIS E NÃO APONTA NENHUM ERRO ESPECÍFICO DAQUELA COMUNIDADE, PORÉM TRAZ UM ALERTA. QUE ALERTA É ESSE? (INTRODUÇÃO DO TEXTO)",
    alternativas: [
      "AS FALSAS DOUTRINAS",
      "AS DEGRADAÇÕES MORAIS",
      "AO CULTO POLITEÍSTA",
      "AS PRÁTICAS PAGÃS",
    ],
    correta: 0,
  },
  {
    id: 'efesios-5',
    secao: 'efesios',
    pergunta: "SEGUNDO A INTRODUÇÃO, QUAL OUTRA CARTA EFÉSIOS TÊM SEMELHANÇA DOUTRINAL? (INTRODUÇÃO DO TEXTO)",
    alternativas: [
      "2 TESSALONICENSES",
      "GÁLATAS",
      "FILIPENSES",
      "COLOSSENSES",
    ],
    correta: 3,
  },
  {
    id: 'efesios-6',
    secao: 'efesios',
    pergunta: "POR VOLTA DE QUAL ANO FOI ESCRITO A CARTA AOS EFÉSIOS? (INTRODUÇÃO DO TEXTO)",
    alternativas: [
      "POR VOLTA DO ANO 70",
      "POR VOLTA DO ANO 90",
      "POR VOLTA DO ANO 60",
      "POR VOLTA DO ANO 80",
    ],
    correta: 1,
  },
  {
    id: 'efesios-7',
    secao: 'efesios',
    pergunta: "NO CAPÍTULO 2, QUAIS FORAM OS TRÊS PEDIDOS QUE PAULO FEZ A DEUS PARA A COMUNIDADE? (EF 2. NOTA DE RODAPÉ PAG 1427)",
    alternativas: [
      "PERSEVERANÇA, ILUMINAÇÃO E SABEDORIA",
      "COMPREENSÃO, AMOR E PACIÊNCIA",
      "SABEDORIA, ILUMINAÇÃO E COMPREENSÃO",
      "INTELIGÊNCIA, COMPREENSÃO E PERSEVERANÇA",
    ],
    correta: 2,
  },
  {
    id: 'efesios-8',
    secao: 'efesios',
    pergunta: "NO CAPÍTULO 2, COMO DEUS É DESCRITO PELO AUTOR? (EF 2, 4-7 NOTA DE RODAPÉ PAG. 1428)",
    alternativas: [
      "RICO EM MISERICÓRDIA, AMOR, FAVOR E BONDADE",
      "AMOR, BENEVOLÊNCIA, PAZ E CARIDADE",
      "BONDADE, JUSTIÇA, AMOR E PAZ",
      "JUSTIÇA, MISERICÓRDIA, AMOR E PACIÊNCIA",
    ],
    correta: 0,
  },
  {
    id: 'efesios-9',
    secao: 'efesios',
    pergunta: "SEGUNDO O AUTOR COMO OS GENTIOS ERAM CHAMADOS PELOS JUDEUS? (EF 2, 11)",
    alternativas: [
      "INCAPAZES",
      "INCIRCUNCIDADOS",
      "INCIRCUNCISOS",
      "IMPUROS",
    ],
    correta: 2,
  },
  {
    id: 'efesios-10',
    secao: 'efesios',
    pergunta: "COMO PAULO SE DESCREVE NO CAPÍTULO 3? (EF 3, 8)",
    alternativas: [
      "O MENOR DE TODOS OS ROMANOS",
      "O MENOR DE TODOS OS DISCÍPULOS",
      "O MENOR DE TODOS OS APÓSTOLOS",
      "O MENOR DE TODOS OS SANTOS",
    ],
    correta: 3,
  },
  {
    id: 'efesios-11',
    secao: 'efesios',
    pergunta: "QUANTOS CARISMAS SÃO ELENCADOS NO CAPÍTULO 4? (EF 4, 11)",
    alternativas: [
      "7 CARISMAS",
      "6 CARISMAS",
      "5 CARISMAS",
      "8 CARISMAS",
    ],
    correta: 2,
  },
  {
    id: 'efesios-12',
    secao: 'efesios',
    pergunta: "NO CAPÍTULO 4, PAULO COMENTA SOBRE A POSTURA DOS GENTIOS QUE VÃO ATRÁS DE PENSAMENTOS VAZIOS, E PEDE PARA QUE O POVO SE AFASTE DE ALGUMAS SITUAÇÕES. QUAIS SÃO ELAS? (EF 4, 31)",
    alternativas: [
      "IMORALIDADE, MESQUINHARIAS, IMPUREZAS, IRA E TODO TIPO DE MALDADE",
      "AMARGURA, IRA, CÓLERA, GRITARIA, DIFAMAÇÃO E TODO TIPO DE MALDADE",
      "OFENSAS, IMORALIDADE, IRA, IMPUREZAS E TODO TIPO DE MALDADE",
      "DESCONTROLE, CÓLERA, AMARGURA, IMPUREZAS E TODO TIPO DE MALDADE",
    ],
    correta: 1,
  },
  {
    id: 'efesios-13',
    secao: 'efesios',
    pergunta: "NO CAPÍTULO 5, PAULO PEDE PARA QUE A CAMINHADA DO POVO SEJA: (EF 5, 8)",
    alternativas: [
      "COMO FILHOS DA LUZ",
      "COMO FILHOS DA MISERICÓRDIA",
      "COMO FILHOS DA JUSTIÇA",
      "COMO FILHOS DA ESPERANÇA",
    ],
    correta: 0,
  },
  {
    id: 'efesios-14',
    secao: 'efesios',
    pergunta: "COMO PAULO COMPARA O CASAMENTO? (EF 5,21-33)",
    alternativas: [
      "COMO A IGREJA E OS APÓSTOLOS",
      "COMO A IGREJA E O PENTECOSTE",
      "COMO CRISTO E O BATISMO",
      "COMO CRISTO E A IGREJA",
    ],
    correta: 3,
  },
  {
    id: 'efesios-15',
    secao: 'efesios',
    pergunta: "O QUE PAULO PEDE PARA QUE NÃO SEJA, NEM SEQUER PRONUNCIADO, PELO POVO DE EFÉSO? (EF 5, 3)",
    alternativas: [
      "OFENSAS, NOME DE DEUSES DE OUTRAS REGIÕES E AVAREZA",
      "RELAÇÕES ILEGÍTIMAS, IMPUREZA E AVAREZA",
      "IMPUREZA, FALSO TESTEMUNHO, MESQUINHARIAS E IMORALIDADE",
      "RELAÇÕES ILEGÍTIMAS, IMORALIDADE, INDECÊNCIA E OFENSAS",
    ],
    correta: 1,
  },
  {
    id: 'efesios-16',
    secao: 'efesios',
    pergunta: "QUAL É O PRIMEIRO MANDAMENTO QUE INCLUI UMA PROMESSA, SEGUNDO PAULO? (EF 6, 2)",
    alternativas: [
      "NÃO LEVANTAR FALSO TESTEMUNHO",
      "AMAR A DEUS SOBRE TODAS AS COISAS",
      "HONRAR PAI E MÃE",
      "GUARDAR DOMINGOS E FESTAS",
    ],
    correta: 2,
  },
  {
    id: 'efesios-17',
    secao: 'efesios',
    pergunta: "COMO PAULO DIZ QUE O EVANGELHO DEVE SER ANUNCIADO? (EF 6, 19-20)",
    alternativas: [
      "COM ARDOR",
      "COM INTELIGÊNCIA",
      "COM SABEDORIA",
      "COM OUSADIA",
    ],
    correta: 3,
  },
  {
    id: 'efesios-18',
    secao: 'efesios',
    pergunta: "COM O QUE PAULO COMPARA A VIDA CRISTÃ? (EF 6, 10-17 NOTA DE RODAPÉ PÁG.1432)",
    alternativas: [
      "COM UM COMBATE",
      "COM UMA CAMINHADA",
      "COM UMA GUERRA",
      "COM UMA SUBIDA A MONTANHA",
    ],
    correta: 0,
  },
  {
    id: 'efesios-19',
    secao: 'efesios',
    pergunta: "QUEM É APONTADO COMO PORTADOR DA CARTA AOS EFÉSIOS? (INTRODUÇÃO DO TEXTO)",
    alternativas: [
      "LUCAS",
      "TEÓFILO",
      "MARCOS",
      "TÍQUICO",
    ],
    correta: 3,
  },
  {
    id: 'efesios-20',
    secao: 'efesios',
    pergunta: "NO CAPÍTULO 2 PAULO COMENTA QUE TODOS PODEM RECEBER A GRAÇA DA SALVAÇÃO. QUAIS POVOS SÃO CITADOS NESSE CAPÍTULO? (EF 2 – TÍTULO DO CAPÍTULO)",
    alternativas: [
      "ASSÍRIOS E MOABITAS",
      "JUDEUS E ASSÍRIOS",
      "JUDEUS E GENTIOS",
      "GENTIOS E ASSÍRIOS",
    ],
    correta: 2,
  },
  {
    id: 'efesios-21',
    secao: 'efesios',
    pergunta: "QUAL É A FINALIDADE DE VESTIR A ARMADURA DE DEUS? (EFÉSIOS 6,10-13)",
    alternativas: [
      "PARA VENCER OS HOMENS QUE SE OPÕEM À FÉ",
      "PARA RESISTIR ÀS MANOBRAS DO DIABO E PERMANECER FIRMES",
      "PARA ALCANÇAR SABEDORIA E CONHECIMENTO ESPIRITUAL",
      "PARA RECEBER OS DONS NECESSÁRIOS AO MINISTÉRIO",
    ],
    correta: 1,
  },
  {
    id: 'efesios-22',
    secao: 'efesios',
    pergunta: "O QUE ACONTECEU COM OS PAGÃOS POR MEIO DO EVANGELHO? (EFÉSIOS 3,6)",
    alternativas: [
      "TORNARAM-SE APENAS SEGUIDORES DA LEI DE MOISÉS",
      "RECEBERAM UMA PROMESSA DIFERENTE DA FEITA AOS JUDEUS",
      "FORAM CHAMADOS A PARTICIPAR DA MESMA HERANÇA, FORMAR O MESMO CORPO E PARTICIPAR DA MESMA PROMESSA",
      "FORAM ESCOLHIDOS PARA OCUPAR O LUGAR DOS APÓSTOLOS",
    ],
    correta: 2,
  },
  {
    id: 'efesios-23',
    secao: 'efesios',
    pergunta: "QUAIS SÃO OS FRUTOS DA LUZ? (EFÉSIOS 5,9)",
    alternativas: [
      "FÉ, ESPERANÇA E CARIDADE",
      "BONDADE, JUSTIÇA E VERDADE",
      "AMOR, PAZ E SABEDORIA",
      "JUSTIÇA, FÉ E OBEDIÊNCIA",
    ],
    correta: 1,
  },
  {
    id: 'efesios-24',
    secao: 'efesios',
    pergunta: "COM O QUE OS CRISTÃOS FORAM SELADOS DEPOIS DE OUVIR E ACREDITAR NO EVANGELHO? (EFÉSIOS 1,13-14)",
    alternativas: [
      "COM A GRAÇA DE DEUS",
      "COM O SANGUE DE CRISTO",
      "COM O ESPÍRITO SANTO DA PROMESSA",
      "COM A PALAVRA DA VERDADE",
    ],
    correta: 2,
  },
  {
    id: 'efesios-25',
    secao: 'efesios',
    pergunta: "O QUE PAULO RECOMENDA AOS FILHOS EM RELAÇÃO AOS PAIS? (EF 6,1-3)",
    alternativas: [
      "QUE SEJAM SUBMISSOS EM TODAS AS COISAS",
      "QUE OBEDEÇAM AOS PAIS NO SENHOR E OS HONREM",
      "QUE ENSINEM OS PAIS NA FÉ",
      "QUE DEIXEM SEUS PAIS PARA SEGUIR CRISTO PERGUNTAS GERAIS",
    ],
    correta: 1,
  },
  {
    id: 'gerais-1',
    secao: 'gerais',
    pergunta: "ESTAMOS EM QUAL EDIÇÃO DO ACAMPAMENTO DE CASAIS?",
    alternativas: [
      "ESTAMOS NA OITAVA EDIÇÃO",
      "ESTAMOS NA DÉCIMA EDIÇÃO",
      "ESTAMOS NA SEXTA EDIÇÃO",
      "ESTAMOS NA SÉTIMA EDIÇÃO",
    ],
    correta: 1,
  },
  {
    id: 'gerais-2',
    secao: 'gerais',
    pergunta: "QUAL É O DIA COMEMORADO PARA HOMENAGEM AO PROFETA ELIAS?",
    alternativas: [
      "21 DE JULHO",
      "20 DE JULHO",
      "22 DE JULHO",
      "23 DE JULHO",
    ],
    correta: 1,
  },
  {
    id: 'gerais-3',
    secao: 'gerais',
    pergunta: "QUAL FOI O DIA QUE FOI A DIVISÃO DAS PARÓQUIAS?",
    alternativas: [
      "05/03/2023",
      "06/03/2023",
      "07/03/2023",
      "08/03/2023",
    ],
    correta: 0,
  },
  {
    id: 'gerais-4',
    secao: 'gerais',
    pergunta: "QUAL É A DATA DE ANIVERSÁRIO DO GRUPO JUREF?",
    alternativas: [
      "5 DE ABRIL",
      "3 DE ABRIL",
      "2 DE ABRIL",
      "16 DE ABRIL",
    ],
    correta: 2,
  },
  {
    id: 'gerais-5',
    secao: 'gerais',
    pergunta: "QUAL É O DIA DO PADRE?",
    alternativas: [
      "5 DE AGOSTO",
      "4 DE AGOSTO",
      "6 DE AGOSTO",
      "7 DE AGOSTO",
    ],
    correta: 1,
  },
  {
    id: 'gerais-6',
    secao: 'gerais',
    pergunta: "QUAL DIA FOI A CRISTOTECA DE 2023?",
    alternativas: [
      "12 DE AGOSTO",
      "8 DE AGOSTO",
      "4 DE AGOSTO",
      "10 DE AGOSTO",
    ],
    correta: 0,
  },
  {
    id: 'gerais-7',
    secao: 'gerais',
    pergunta: "QUAL FOI O ÚLTIMO ACAMPAMENTO ANTES DA PANDEMIA?",
    alternativas: [
      "FAC",
      "MIRIM",
      "CES",
      "JUVENIL",
    ],
    correta: 1,
  },
  {
    id: 'gerais-8',
    secao: 'gerais',
    pergunta: "QUAL É O DIA DA BENÇÃO DOS ANIMAIS NA COMUNIDADE SÃO FRANCISCO DE ASSIS?",
    alternativas: [
      "3 DE OUTUBRO",
      "5 DE OUTUBRO",
      "4 DE OUTUBRO",
      "6 DE OUTUBRO",
    ],
    correta: 2,
  },
  {
    id: 'gerais-9',
    secao: 'gerais',
    pergunta: "QUAL SIGNIFICADO DOS TRÊS NÓS NO CORDÃO DE SÃO FRANCISCO?",
    alternativas: [
      "AMOR, OBEDIÊNCIA E CASTIDADE",
      "HUMILDADE, OBEDIÊNCIA E CASTIDADE",
      "POBREZA, OBEDIÊNCIA E CASTIDADE",
      "SOLIDARIEDADE, OBEDIÊNCIA E CASTIDADE",
    ],
    correta: 2,
  },
  {
    id: 'gerais-10',
    secao: 'gerais',
    pergunta: "QUANDO FOI A SEMANA DA FAMÍLIA NO ANO DE 2022?",
    alternativas: [
      "13 Á 21 DE AGOSTO",
      "07 Á 14 DE AGOSTO",
      "10 Á 17 DE AGOSTO",
      "12 Á 19 DE AGOSTO",
    ],
    correta: 0,
  },
  {
    id: 'gerais-11',
    secao: 'gerais',
    pergunta: "QUAL A DATA DO RETIRO VOCACIONAL CARMELITA EM 2017?",
    alternativas: [
      "21 Á 23 DE JULHO",
      "20 Á 24 DE JULHO",
      "22 Á 24 DE JULHO",
      "20 Á 22 DE JULHO",
    ],
    correta: 0,
  },
  {
    id: 'gerais-12',
    secao: 'gerais',
    pergunta: "O QUE LEVOU SANTA TEREZINHA ATÉ A MORTE?",
    alternativas: [
      "FOI PERSEGUIDA E MORTA POR HOMENS QUE NÃO GOSTAVAM DE JESUS",
      "GRIPE",
      "TUBERCULOSE",
      "SOFREU UM DERRAME",
    ],
    correta: 2,
  },
  {
    id: 'gerais-13',
    secao: 'gerais',
    pergunta: "QUAL A PADROEIRA DO PARANÁ?",
    alternativas: [
      "NOSSA SENHORA DO PERPÉTUO SOCORRO",
      "NOSSA SENHORA DA LUZ DOS PINHAIS",
      "NOSSA SENHORA AUXILIADORA",
      "NOSSA SENHORA DO ROCIO",
    ],
    correta: 3,
  },
  {
    id: 'gerais-14',
    secao: 'gerais',
    pergunta: "QUEM CANONIZOU SANTA TERESINHA?",
    alternativas: [
      "FOI O PAPA PIO XI",
      "FOI O PAPA PIO XII",
      "FOI O PAPA PIO X",
      "FOI O PAPA PIO VII",
    ],
    correta: 0,
  },
  {
    id: 'gerais-15',
    secao: 'gerais',
    pergunta: "QUAL ERA O NOME DE SÃO FRANCISCO?",
    alternativas: [
      "GIOVANNI DI PIETRO",
      "FRANCISCO DE ASSIS",
      "GIOVANNE DE PIETRO",
      "DJIOVANNE DE PIETRO",
    ],
    correta: 0,
  },
  {
    id: 'gerais-16',
    secao: 'gerais',
    pergunta: "QUAL O VERDADEIRO NOME DE SANTO ANTÔNIO?",
    alternativas: [
      "FERNANDO",
      "FRANCISCO",
      "FREDERICO",
      "LUCAS",
    ],
    correta: 0,
  },
  {
    id: 'gerais-17',
    secao: 'gerais',
    pergunta: "EM QUAL DIA EM 2025 FOI FEITO O TERÇO LUMINOSO NA COMUNIDADE SÃO FRANCISCO DE ASSIS?",
    alternativas: [
      "12 DE AGOSTO",
      "11 DE AGOSTO",
      "10 DE AGOSTO",
      "05 DE AGOSTO",
    ],
    correta: 0,
  },
  {
    id: 'gerais-18',
    secao: 'gerais',
    pergunta: "O QUE SIGNIFICA A PALAVRA CARMELO?",
    alternativas: [
      "MONTE",
      "ESPERANÇA",
      "JARDIM",
      "HARMONIA",
    ],
    correta: 2,
  },
  {
    id: 'gerais-19',
    secao: 'gerais',
    pergunta: "QUAL FOI A EDIÇÃO DE 2025 DA SJJ?",
    alternativas: [
      "DÉCIMA TERCEIRA",
      "DÉCIMA QUARTA",
      "DÉCIMA QUINTA",
      "NONA",
    ],
    correta: 1,
  },
  {
    id: 'gerais-20',
    secao: 'gerais',
    pergunta: "ONDE FICA O MONTE CARMELO?",
    alternativas: [
      "EGITO",
      "ISRAEL",
      "GRÉCIA",
      "ROMA",
    ],
    correta: 1,
  },
  {
    id: 'gerais-21',
    secao: 'gerais',
    pergunta: "QUAIS SÃO OS DOIS SACRAMENTOS DE SERVIÇO?",
    alternativas: [
      "EUCARISTIA E CRISMA",
      "ORDEM E MATRIMÔNIO",
      "BATISMO E CRISMA",
      "BATISMO E CONFISSÃO",
    ],
    correta: 1,
  },
  {
    id: 'gerais-22',
    secao: 'gerais',
    pergunta: "QUAL É A COR QUE USAMOS PARA OS MÁRTIRES?",
    alternativas: [
      "ROXO",
      "VERMELHO",
      "BRANCO",
      "VERDE",
    ],
    correta: 1,
  },
  {
    id: 'gerais-23',
    secao: 'gerais',
    pergunta: "QUAIS SÃO OS DONS DO ESPÍRITO SANTO?",
    alternativas: [
      "SABEDORIA, ENTENDIMENTO, CONSELHO, FORTALEZA, AMOR DE DEUS, PIEDADE E CIÊNCIA",
      "ENTENDIMENTO, CONSELHO, CIÊNCIA, TEMOR DE DEUS, FORTALEZA, PAZ E PIEDADE",
      "CIÊNCIA, SABEDORIA, TEMOR DE DEUS, FORTALEZA, PIEDADE, ENTENDIMENTO E CONSELHO",
      "FORTALEZA, TEMOR DE DEUS, CARIDADE, PIEDADE, CIÊNCIA, SABEDORIA E TEMOR DE DEUS",
    ],
    correta: 2,
  },
  {
    id: 'gerais-24',
    secao: 'gerais',
    pergunta: "QUANTOS SÃO OS SACRAMENTOS DA INICIAÇÃO CRISTÃ?",
    alternativas: [
      "2 SACRAMENTOS",
      "3 SACRAMENTOS",
      "4 SACRAMENTOS",
      "5 SACRAMENTOS",
    ],
    correta: 1,
  },
  {
    id: 'gerais-25',
    secao: 'gerais',
    pergunta: "QUANTAS ETAPAS DA CATEQUESE SÃO NECESSÁRIAS PARA FAZER O SACRAMENTO DA CONFIRMAÇÃO?",
    alternativas: [
      "3 ETAPAS",
      "4 ETAPAS",
      "5 ETAPAS",
      "6 ETAPAS",
    ],
    correta: 2,
  },
];
